//
// Created by Henrique on 23-Jul-21.
//

#ifndef CNN_GPU_CNN_ERRORS_LIST_H
#define CNN_GPU_CNN_ERRORS_LIST_H

#define TENSOR_MASK_ERROR -90
#define TENSOR_INVALID_FLAG_TYPE -1 + TENSOR_MASK_ERROR
#define TENSOR_INVALID_FLAG_MEM -2 + TENSOR_MASK_ERROR
#define TENSOR_INVALID_FLAG_DIM -3 + TENSOR_MASK_ERROR

#define NULL_PARAM -4 + TENSOR_MASK_ERROR
#define TENSOR_OUT_MEMORY -5 + TENSOR_MASK_ERROR

#define FILE_MASK_ERROR -100
#define FAILED_LOAD_FILE -1+FILE_MASK_ERROR
#define INVALID_FILTER_SIZE -2+FILE_MASK_ERROR
#define CNN_LUA_ERROR -3+FILE_MASK_ERROR
#define FAILED_SET_DIR -4+FILE_MASK_ERROR

#endif //CNN_GPU_CNN_ERRORS_LIST_H
