//
// Created by Henrique on 14/08/2021.
//
const char __default_kernel__[] = 
/*1*/		"#ifndef GAB_KERNELS_OPENCL_H\n"
/*2*/		"#define GAB_KERNELS_OPENCL_H\n"
/*3*/		"//utils.h\n"
/*4*/		"// Created by Xx220xX on 10/05/2020.\n"
/*5*/		"#ifndef ATIVATIONSFUNCTIONS_H\n"
/*6*/		"#define ATIVATIONSFUNCTIONS_H\n"
/*7*/		"#define USEFLOAT 1\n"
/*8*/		"\n"
/*9*/		"#if (USEFLOAT == 1)\n"
/*10*/		"#define  REAL float\n"
/*11*/		"#define TANH tanh\n"
/*12*/		"#define EXP exp\n"
/*13*/		"#define SQRT sqrt\n"
/*14*/		"#else\n"
/*15*/		"#define  REAL double\n"
/*16*/		"#define TANH tanh\n"
/*17*/		"#define EXP exp\n"
/*18*/		"#define SQRT sqrt\n"
/*19*/		"#endif\n"
/*20*/		"#define Vector __global REAL *\n"
/*21*/		"\n"
/*22*/		"#define kV __kernel void\n"
/*23*/		"\n"
/*24*/		"#define KTensorMap(x, y, z, tx, ty)((z)*(ty*tx)+(x)*ty+(y))\n"
/*25*/		"\n"
/*26*/		"#define KTensorMap4D(x, y, z, l, tx, ty, tz)((l)*(ty)*(tx)*(tz)+(z)*(ty*tx)+(x)*ty+(y))\n"
/*27*/		"\n"
/*28*/		"#define KTensorRemap4D(total, _x_, _y_, _z_, _l_, tx, ty, tz)\\\n"
/*29*/		"_y_ = total%ty      ;                                        \\\n"
/*30*/		"_x_ = (total - _y_)%(ty*tx)/ty ;                             \\\n"
/*31*/		"_z_ = (total- _x_*ty - _y_)%(tx*ty*tz)/(ty*tx)  ;            \\\n"
/*32*/		"_l_ = (total -_z_*tx*ty -_x_*ty - _y_)/(tx*ty*tz);\n"
/*33*/		"\n"
/*34*/		"\n"
/*35*/		"#define KTensorRemap(total, _x_, _y_, _z_, tx, ty)\\\n"
/*36*/		"_y_ = total % ty;\\\n"
/*37*/		"_x_ = ((total - _y_) % (ty * tx)) / ty;\\\n"
/*38*/		"_z_ = (k - _x_ * ty - _y_) / (tx * ty);\n"
/*39*/		"\n"
/*40*/		"#define KTensorRemap2D(total, x, y, ty)\\\n"
/*41*/		"y = total % ty;\\\n"
/*42*/		"x = total/ ty;\n"
/*43*/		"\n"
/*44*/		"typedef struct {\n"
/*45*/		"	int x, y, z;\n"
/*46*/		"} Ponto3d;\n"
/*47*/		"\n"
/*48*/		"typedef struct {\n"
/*49*/		"	Ponto3d min, max;\n"
/*50*/		"} Range;\n"
/*51*/		"\n"
/*52*/		"\n"
/*53*/		"REAL sigmoid(REAL x) {\n"
/*54*/		"	return 1.0 / (1.0 + EXP(-x));\n"
/*55*/		"}\n"
/*56*/		"\n"
/*57*/		"REAL difsigmoid(REAL x) {\n"
/*58*/		"	REAL tmp = sigmoid(x);\n"
/*59*/		"	return tmp * (1.0 - tmp);\n"
/*60*/		"}\n"
/*61*/		"\n"
/*62*/		"REAL tanghG(REAL x) {\n"
/*63*/		"	return TANH(x);\n"
/*64*/		"}\n"
/*65*/		"\n"
/*66*/		"REAL diftanhG(REAL x) {\n"
/*67*/		"	REAL tmp = TANH(x);\n"
/*68*/		"	return (1.0 - tmp * tmp);\n"
/*69*/		"}\n"
/*70*/		"\n"
/*71*/		"REAL relu(REAL x) {\n"
/*72*/		"	return x > 0 ? x : 0.0;\n"
/*73*/		"}\n"
/*74*/		"\n"
/*75*/		"REAL difrelu(REAL x) {\n"
/*76*/		"	return x > 0 ? 1.0 : 0.0;\n"
/*77*/		"}\n"
/*78*/		"\n"
/*79*/		"REAL func(unsigned int id, REAL x) {\n"
/*80*/		"	switch (id) {\n"
/*81*/		"		case 0:\n"
/*82*/		"			return sigmoid(x);\n"
/*83*/		"		case 1:\n"
/*84*/		"			return difsigmoid(x);\n"
/*85*/		"		case 2:\n"
/*86*/		"			return tanghG(x);\n"
/*87*/		"		case 3:\n"
/*88*/		"			return diftanhG(x);\n"
/*89*/		"		case 4:\n"
/*90*/		"			return relu(x);\n"
/*91*/		"		case 5:\n"
/*92*/		"			return difrelu(x);\n"
/*93*/		"		case 6:\n"
/*94*/		"			return x;\n"
/*95*/		"		case 7:\n"
/*96*/		"			return 1;\n"
/*97*/		"		default:\n"
/*98*/		"			return 0;\n"
/*99*/		"	}\n"
/*100*/		"}\n"
/*101*/		"\n"
/*102*/		"#endif\n"
/*103*/		"//bathnorm.h\n"
/*104*/		"\n"
/*105*/		"/// achar a media\n"
/*106*/		"/// ativa 1\n"
/*107*/		"kV BatchNormMedia(Vector entrada, Vector media,\n"
/*108*/		"				  int entradatx, int entradaty, int k0) {\n"
/*109*/		"	int z = get_global_id(0) + k0;\n"
/*110*/		"	int x, y;\n"
/*111*/		"	REAL m = 0;\n"
/*112*/		"	for (x = 0; x < entradatx; x++) {\n"
/*113*/		"		for (y = 0; y < entradaty; y++) {\n"
/*114*/		"			m += entrada[KTensorMap(x, y, z, entradatx, entradaty)];\n"
/*115*/		"		}\n"
/*116*/		"	}\n"
/*117*/		"	media[z] = m / (REAL)(entradatx * entradaty);\n"
/*118*/		"}\n"
/*119*/		"\n"
/*120*/		"/// achar a diferenca\n"
/*121*/		"/// ativa 2\n"
/*122*/		"kV BatchNormDiferenca(Vector entrada, Vector media,\n"
/*123*/		"					  Vector diferenca,\n"
/*124*/		"					  Vector diferencaquad,\n"
/*125*/		"					  int entradatx, int entradaty, int k0) {\n"
/*126*/		"	int x, y, z;\n"
/*127*/		"	int k = get_global_id(0) + k0;\n"
/*128*/		"	KTensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*129*/		"	diferenca[k] = entrada[k] - media[z];\n"
/*130*/		"	diferencaquad[k] = diferenca[k] * diferenca[k];\n"
/*131*/		"}\n"
/*132*/		"/// ativa 3\n"
/*133*/		"\n"
/*134*/		"kV BatchNormVariance(Vector dif, Vector difQuad,\n"
/*135*/		"					 Vector sumdiferenca, Vector variancia,\n"
/*136*/		"					 REAL episolon, int diftx, int difty,\n"
/*137*/		"					 int k0) {\n"
/*138*/		"	int z = get_global_id(0) + k0;\n"
/*139*/		"	REAL sum = 0;\n"
/*140*/		"	REAL sumdif = 0;\n"
/*141*/		"	for (int x = 0; x < diftx; x++) {\n"
/*142*/		"		for (int y = 0; y < difty; y++) {\n"
/*143*/		"			sum += difQuad[KTensorMap(x, y, z, diftx, difty)];\n"
/*144*/		"			sumdif += dif[KTensorMap(x, y, z, diftx, difty)];\n"
/*145*/		"		}\n"
/*146*/		"	}\n"
/*147*/		"	sumdiferenca[z] = sumdif;\n"
/*148*/		"	variancia[z] = SQRT(sum / (difty * diftx) + episolon);\n"
/*149*/		"}\n"
/*150*/		"\n"
/*151*/		"/// normaliza\n"
/*152*/		"/// ativa 4\n"
/*153*/		"\n"
/*154*/		"kV BatchNormNormaliza(Vector saida,\n"
/*155*/		"					  Vector norma,\n"
/*156*/		"					  Vector diferenca,\n"
/*157*/		"					  Vector variancia,\n"
/*158*/		"					  Vector Y,\n"
/*159*/		"					  Vector B,\n"
/*160*/		"					  int diferencatx, int diferencaty, int k0) {\n"
/*161*/		"	int x, y, z;\n"
/*162*/		"	int k = get_global_id(0) + k0;\n"
/*163*/		"	KTensorRemap(k, x, y, z, diferencatx, diferencaty)\n"
/*164*/		"	norma[k] = diferenca[k] / variancia[z];\n"
/*165*/		"	saida[k] = norma[k] * Y[z] + B[z];\n"
/*166*/		"}\n"
/*167*/		"\n"
/*168*/		"\n"
/*169*/		"kV BatchNormaCalcGrad1(Vector gradIn,\n"
/*170*/		"					   Vector gradNext,\n"
/*171*/		"					   Vector variancia,\n"
/*172*/		"					   Vector media,\n"
/*173*/		"					   Vector Y,\n"
/*174*/		"					   Vector somaDif,\n"
/*175*/		"					   Vector entrada,\n"
/*176*/		"					   int entradatx,\n"
/*177*/		"					   int entradaty,\n"
/*178*/		"					   int k0) {\n"
/*179*/		"	int x, y, z;\n"
/*180*/		"	int k = get_global_id(0) + k0;\n"
/*181*/		"	KTensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*182*/		"	REAL M = entradatx * entradaty;\n"
/*183*/		"	REAL dif_variance = somaDif[z] - entrada[k] + media[z] + (entrada[k] - media[z]) * (M - 1);\n"
/*184*/		"	dif_variance = dif_variance * -1.0 / (variancia[z] * M * M);\n"
/*185*/		"\n"
/*186*/		"	REAL didx = variancia[z] * (M - 1 / M) + (media[z] - entrada[k]) * dif_variance;\n"
/*187*/		"	didx = didx / (variancia[z] * variancia[z]);\n"
/*188*/		"	didx = didx * gradNext[k];\n"
/*189*/		"	gradIn[k] = didx * Y[z];\n"
/*190*/		"}\n"
/*191*/		"kV BatchNormaCalcGrad2(Vector gradNext,\n"
/*192*/		"					   Vector norma,\n"
/*193*/		"					   Vector Y,\n"
/*194*/		"					   Vector B,\n"
/*195*/		"					   Vector gradY,\n"
/*196*/		"					   Vector gradB,\n"
/*197*/		"					   REAL hitlearn,\n"
/*198*/		"					   REAL momento,\n"
/*199*/		"					   REAL weightDecay,\n"
/*200*/		"					   int entradatx,\n"
/*201*/		"					   int entradaty,\n"
/*202*/		"					   int k0) {\n"
/*203*/		"	int z = get_global_id(0) + k0;\n"
/*204*/		"	REAL sumY = 0;\n"
/*205*/		"	REAL sumB = 0;\n"
/*206*/		"	int k;\n"
/*207*/		"	for (int x = 0; x < entradatx; ++x) {\n"
/*208*/		"		for (int y = 0; y < entradaty; ++y) {\n"
/*209*/		"			k = KTensorMap(x, y, z, entradatx, entradaty);\n"
/*210*/		"			sumY += gradNext[k];\n"
/*211*/		"			sumB += gradNext[k] * norma[k];\n"
/*212*/		"		}\n"
/*213*/		"	}\n"
/*214*/		"	gradB[z] = sumB + gradB[z] * momento;\n"
/*215*/		"	gradY[z] = sumY + gradY[z] * momento;\n"
/*216*/		"\n"
/*217*/		"	B[z] = B[z] - (gradB[z] + weightDecay * B[z]) * hitlearn;\n"
/*218*/		"	Y[z] = Y[z] - (gradY[z] + weightDecay * Y[z]) * hitlearn;\n"
/*219*/		"}\n"
/*220*/		"\n"
/*221*/		"\n"
/*222*/		"\n"
/*223*/		"//cnnutils.h\n"
/*224*/		"//\n"
/*225*/		"// Created by Henrique on 22-Jul-21.\n"
/*226*/		"//\n"
/*227*/		"\n"
/*228*/		"\n"
/*229*/		"kV createImg(__global unsigned char *out, Vector v, int vx, int vy, int imi, int imy, int k0) {\n"
/*230*/		"	int k = get_global_id(0) + k0;\n"
/*231*/		"	int i, j, z;\n"
/*232*/		"	KTensorRemap(k, i, j, z, vx, vy)\n"
/*233*/		"	imi = imi + i;\n"
/*234*/		"	int imj = j + z * vy + z;\n"
/*235*/		"	out[imi * imy + imj] = ((int) v[k]) & 0xff;\n"
/*236*/		"}\n"
/*237*/		"\n"
/*238*/		"kV putIMG(__global unsigned char *imagem_saida,\n"
/*239*/		"		  Vector v,\n"
/*240*/		"		  int z,\n"
/*241*/		"		  REAL px,\n"
/*242*/		"		  REAL py,\n"
/*243*/		"		  int imy,\n"
/*244*/		"		  int width,\n"
/*245*/		"		  int i0,\n"
/*246*/		"		  int j0,\n"
/*247*/		"		  int vx,\n"
/*248*/		"		  int vy,\n"
/*249*/		"		  int k0) {\n"
/*250*/		"	int k = get_global_id(0) + k0;\n"
/*251*/		"	int i, j;\n"
/*252*/		"	KTensorRemap2D(k, i, j, imy)\n"
/*253*/		"	int x = i * px, y = j * py;\n"
/*254*/		"	imagem_saida[(i + i0) * width + j + j0] = ((int) v[KTensorMap(x, y, z, vx, vy)]) & 0xff;\n"
/*255*/		"}\n"
/*256*/		"\n"
/*257*/		"\n"
/*258*/		"kV normalizeVector(Vector input, Vector saida, REAL multiplicador, REAL somador, REAL subtrator,\n"
/*259*/		"				   int k0) {\n"
/*260*/		"	int k = get_global_id(0) + k0;\n"
/*261*/		"	saida[k] = (input[k] + somador) * multiplicador - subtrator;\n"
/*262*/		"}\n"
/*263*/		"\n"
/*264*/		"\n"
/*265*/		"kV kernel_sub(Vector ds, Vector s, Vector t, int k0) {\n"
/*266*/		"	int k = get_global_id(0) + k0;\n"
/*267*/		"	ds[k] = s[k] - t[k];\n"
/*268*/		"}\n"
/*269*/		"\n"
/*270*/		"kV kernel_normalizechar2real(Vector dst, __global char *src, REAL a, REAL b, int k0) {\n"
/*271*/		"	int k = get_global_id(0) + k0;\n"
/*272*/		"	dst[k] = ((REAL)src[k] - b) / a;\n"
/*273*/		"}\n"
/*274*/		"\n"
/*275*/		"kV kernel_getVetorClassFromChar( Vector dst, __global unsigned char *ints,int noptiobs, int k0) {\n"
/*276*/		"	int w = get_global_id(0) + k0;\n"
/*277*/		"	int y = ints[w];\n"
/*278*/		"	dst[KTensorMap4D(0, y, 0, w, 1, noptiobs, 1)] = 1.0;\n"
/*279*/		"}\n"
/*280*/		"\n"
/*281*/		"//conv.h\n"
/*282*/		"kV convSum(Vector filtro, Vector entrada, Vector saida,\n"
/*283*/		"           int passox, int passoy,\n"
/*284*/		"           int saidatx, int saidaty,\n"
/*285*/		"           int entradatx, int entradaty,\n"
/*286*/		"           int fx, int fy, int fz, int k0) {\n"
/*287*/		"	int k = get_global_id(0) + k0;\n"
/*288*/		"	int x, y, filtrok;\n"
/*289*/		"	KTensorRemap(k, x, y, filtrok, saidatx, saidaty)\n"
/*290*/		"	REAL sum = 0, f = 0, v = 0;\n"
/*291*/		"	int lf = 0, le = 0;\n"
/*292*/		"	for (int m = 0; m < fx; m++) {\n"
/*293*/		"		for (int n = 0; n < fy; n++) {\n"
/*294*/		"			for (int z = 0; z < fz; z++) {\n"
/*295*/		"				lf = KTensorMap4D(m, n, z, filtrok, fx, fy, fz);\n"
/*296*/		"				le = KTensorMap(x * passox + m, y * passoy + n, z, entradatx, entradaty);\n"
/*297*/		"				f = filtro[lf];\n"
/*298*/		"				v = entrada[le];\n"
/*299*/		"				sum += f * v;\n"
/*300*/		"			}\n"
/*301*/		"		}\n"
/*302*/		"	}\n"
/*303*/		"	saida[k] = sum;\n"
/*304*/		"}\n"
/*305*/		"\n"
/*306*/		"\n"
/*307*/		"kV convCalcGradAndFixWeight(Vector filtros, Vector ds,\n"
/*308*/		"                            Vector entrada, Vector gradFiltro,\n"
/*309*/		"                            int fx, int fy, int fz,\n"
/*310*/		"                            int entrada_tx, int entrada_ty,\n"
/*311*/		"                            int saida_tx, int saida_ty,\n"
/*312*/		"                            int passox, int passoy,\n"
/*313*/		"                            REAL hitLearn, REAL momento, REAL weightDecay,\n"
/*314*/		"                            int k0) {\n"
/*315*/		"	int k = get_global_id(0) + k0;\n"
/*316*/		"	int m, n, z, l;\n"
/*317*/		"	KTensorRemap4D(k, m, n, z, l, fx, fy, fz)\n"
/*318*/		"	REAL soma = 0;\n"
/*319*/		"	int le, ls;\n"
/*320*/		"	for (int i = 0; i < saida_tx; ++i) {\n"
/*321*/		"		for (int j = 0; j < saida_ty; ++j) {\n"
/*322*/		"			le = KTensorMap(i * passox + m, j * passoy + n, z, entrada_tx, entrada_ty);\n"
/*323*/		"			ls = KTensorMap(i, j, l, saida_tx, saida_ty);\n"
/*324*/		"			soma += entrada[le]\n"
/*325*/		"			        * ds[ls];\n"
/*326*/		"		}\n"
/*327*/		"	}\n"
/*328*/		"	REAL dw = soma + gradFiltro[k] * momento;\n"
/*329*/		"	REAL w = filtros[k];\n"
/*330*/		"	filtros[k] = w - hitLearn * (dw + w * weightDecay);\n"
/*331*/		"	gradFiltro[k] = dw;\n"
/*332*/		"}\n"
/*333*/		"\n"
/*334*/		"kV convCalcGradIn(Vector filtro, Vector gradEntrada, Vector gradNext,\n"
/*335*/		"                  int fx, int fy, int fz,\n"
/*336*/		"                  int passox, int passoy,\n"
/*337*/		"                  int entradatx, int entradaty,\n"
/*338*/		"                  int saidatx, int saidaty, int saidatz,\n"
/*339*/		"                  int k0) {\n"
/*340*/		"	int k = get_global_id(0) + k0;\n"
/*341*/		"	int x, y, z;\n"
/*342*/		"	KTensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*343*/		"\n"
/*344*/		"	Range range_filtro;\n"
/*345*/		"	range_filtro.min.x = 0;\n"
/*346*/		"	if (x + fx > entradatx) {\n"
/*347*/		"		range_filtro.min.x = x + fx - entradatx;\n"
/*348*/		"	}\n"
/*349*/		"	range_filtro.max.x = fx - 1;\n"
/*350*/		"	if (x - fx + 1 < 0) {\n"
/*351*/		"		range_filtro.max.x = x;\n"
/*352*/		"	}\n"
/*353*/		"	range_filtro.min.y = 0;\n"
/*354*/		"	if (y + fy > entradaty) {\n"
/*355*/		"		range_filtro.min.y = y + fy - entradaty;\n"
/*356*/		"	}\n"
/*357*/		"	range_filtro.max.y = fy - 1;\n"
/*358*/		"	if (y - fy + 1 < 0) {\n"
/*359*/		"		range_filtro.max.y = y;\n"
/*360*/		"	}\n"
/*361*/		"	REAL somaErro = 0, pesoAplicado = 0;\n"
/*362*/		"	int i, j;\n"
/*363*/		"	int lf, ls;\n"
/*364*/		"	for (int m = range_filtro.min.x; m <= range_filtro.max.x; m++) {\n"
/*365*/		"		i = (x - m) / passox;\n"
/*366*/		"		if (i * passox + m != x) continue;\n"
/*367*/		"		for (int n = range_filtro.min.y; n <= range_filtro.max.y; n++) {\n"
/*368*/		"			j = (y - n) / passoy;\n"
/*369*/		"			if (j * passoy + n != y) continue;\n"
/*370*/		"			for (int w = 0; w < saidatz; w++) {\n"
/*371*/		"				lf = KTensorMap4D(m, n, z, w, fx, fy, fz);\n"
/*372*/		"				ls = KTensorMap(i, j, w, saidatx, saidaty);\n"
/*373*/		"				pesoAplicado = filtro[lf];\n"
/*374*/		"				somaErro += pesoAplicado * gradNext[ls];\n"
/*375*/		"			}\n"
/*376*/		"		}\n"
/*377*/		"	}\n"
/*378*/		"	gradEntrada[k] = somaErro;\n"
/*379*/		"}\n"
/*380*/		"\n"
/*381*/		"\n"
/*382*/		"//convf.h\n"
/*383*/		"kV convFSum(Vector filtro, Vector entrada, Vector Z, Vector saida,\n"
/*384*/		"			int passox, int passoy,\n"
/*385*/		"			int saidatx, int saidaty,\n"
/*386*/		"			int entradatx, int entradaty,\n"
/*387*/		"			int fx, int fy, int fz, int fid, int k0) {\n"
/*388*/		"	int k = get_global_id(0) + k0;\n"
/*389*/		"	int x, y, filtrok;\n"
/*390*/		"\n"
/*391*/		"	KTensorRemap(k, x, y, filtrok, saidatx, saidaty)\n"
/*392*/		"	REAL sum = 0, f, v;\n"
/*393*/		"	int lf, le;\n"
/*394*/		"	for (int m = 0; m < fx; m++) {\n"
/*395*/		"		for (int n = 0; n < fy; n++) {\n"
/*396*/		"			for (int z = 0; z < fz; z++) {\n"
/*397*/		"				lf = KTensorMap4D(m, n, z, filtrok, fx, fy, fz);\n"
/*398*/		"				le = KTensorMap(x * passox + m, y * passoy + n, z, entradatx, entradaty);\n"
/*399*/		"				f = filtro[lf];\n"
/*400*/		"				v = entrada[le];\n"
/*401*/		"				sum += f * v;\n"
/*402*/		"			}\n"
/*403*/		"		}\n"
/*404*/		"	}\n"
/*405*/		"	Z[k] = sum;\n"
/*406*/		"	saida[k] = func(fid, sum);\n"
/*407*/		"}\n"
/*408*/		"\n"
/*409*/		"kV convFCalcGradZ(Vector ds, Vector z, Vector dz, int fid, int k0) {\n"
/*410*/		"	int k = get_global_id(0) + k0;\n"
/*411*/		"	dz[k] = ds[k] * func(fid, z[k]);\n"
/*412*/		"}\n"
/*413*/		"\n"
/*414*/		"\n"
/*415*/		"\n"
/*416*/		"kV convFCalcGradIn(Vector filtro, Vector gradEntrada, Vector dz,\n"
/*417*/		"				   int fx, int fy, int fz,\n"
/*418*/		"				   int passox, int passoy,\n"
/*419*/		"				   int entradatx, int entradaty,\n"
/*420*/		"				   int saidatx, int saidaty, int saidatz,\n"
/*421*/		"				   int k0) {\n"
/*422*/		"	int k = get_global_id(0) + k0;\n"
/*423*/		"	int x, y, z;\n"
/*424*/		"	KTensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*425*/		"\n"
/*426*/		"	Range range_filtro;\n"
/*427*/		"	range_filtro.min.x = 0;\n"
/*428*/		"	if (x + fx > entradatx) {\n"
/*429*/		"		range_filtro.min.x = x + fx - entradatx;\n"
/*430*/		"	}\n"
/*431*/		"	range_filtro.max.x = fx - 1;\n"
/*432*/		"	if (x - fx + 1 < 0) {\n"
/*433*/		"		range_filtro.max.x = x;\n"
/*434*/		"	}\n"
/*435*/		"	range_filtro.min.y = 0;\n"
/*436*/		"	if (y + fy > entradaty) {\n"
/*437*/		"		range_filtro.min.y = y + fy - entradaty;\n"
/*438*/		"	}\n"
/*439*/		"	range_filtro.max.y = fy - 1;\n"
/*440*/		"	if (y - fy + 1 < 0) {\n"
/*441*/		"		range_filtro.max.y = y;\n"
/*442*/		"	}\n"
/*443*/		"	REAL somaErro = 0, pesoAplicado = 0;\n"
/*444*/		"	int i, j;\n"
/*445*/		"	int lf, ls;\n"
/*446*/		"	for (int m = range_filtro.min.x; m <= range_filtro.max.x; m++) {\n"
/*447*/		"		i = (x - m) / passox;\n"
/*448*/		"		if (i * passox + m != x) continue;\n"
/*449*/		"		for (int n = range_filtro.min.y; n <= range_filtro.max.y; n++) {\n"
/*450*/		"			j = (y - n) / passoy;\n"
/*451*/		"			if (j * passoy + n != y) continue;\n"
/*452*/		"			for (int w = 0; w < saidatz; w++) {\n"
/*453*/		"				lf = KTensorMap4D(m, n, z, w, fx, fy, fz);\n"
/*454*/		"				ls = KTensorMap(i, j, w, saidatx, saidaty);\n"
/*455*/		"				pesoAplicado = filtro[lf];\n"
/*456*/		"				somaErro += pesoAplicado * dz[ls];\n"
/*457*/		"			}\n"
/*458*/		"		}\n"
/*459*/		"	}\n"
/*460*/		"	gradEntrada[k] = somaErro;\n"
/*461*/		"}\n"
/*462*/		"\n"
/*463*/		"kV convFCalcGradAndFixWeight(Vector filtros, Vector dz,\n"
/*464*/		"							 Vector entrada, Vector gradFiltro,\n"
/*465*/		"							 int fx, int fy, int fz,\n"
/*466*/		"							 int entrada_tx, int entrada_ty,\n"
/*467*/		"							 int saida_tx, int saida_ty,\n"
/*468*/		"							 int passox, int passoy,\n"
/*469*/		"							 REAL hitLearn, REAL momento, REAL weightDecay,\n"
/*470*/		"							 int k0) {\n"
/*471*/		"	int k = get_global_id(0) + k0;\n"
/*472*/		"	int m, n, z, l;\n"
/*473*/		"	KTensorRemap4D(k, m, n, z, l, fx, fy, fz)\n"
/*474*/		"	REAL soma = 0;\n"
/*475*/		"	int le, ls;\n"
/*476*/		"	for (int i = 0; i < saida_tx; ++i) {\n"
/*477*/		"		for (int j = 0; j < saida_ty; ++j) {\n"
/*478*/		"			le = KTensorMap(i * passox + m, j * passoy + n, z, entrada_tx, entrada_ty);\n"
/*479*/		"			ls = KTensorMap(i, j, l, saida_tx, saida_ty);\n"
/*480*/		"			soma += entrada[le]\n"
/*481*/		"					* dz[ls];\n"
/*482*/		"		}\n"
/*483*/		"	}\n"
/*484*/		"	REAL dw = soma + gradFiltro[k] * momento;\n"
/*485*/		"	REAL w = filtros[k];\n"
/*486*/		"	filtros[k] = w - hitLearn * (dw + w * weightDecay);\n"
/*487*/		"	gradFiltro[k] = dw;\n"
/*488*/		"}\n"
/*489*/		"//convNc.h\n"
/*490*/		"\n"
/*491*/		"kV convncSum(Vector W, Vector A, Vector Z, Vector S,\n"
/*492*/		"			 unsigned int fid,\n"
/*493*/		"			 unsigned int passox, int passoy,\n"
/*494*/		"			 unsigned int largx, unsigned int largy,\n"
/*495*/		"			 unsigned int entradatx, unsigned int entradaty,\n"
/*496*/		"			 unsigned int saidatx, unsigned int saidaty,\n"
/*497*/		"			 unsigned int fx, unsigned int fy, unsigned int fz,\n"
/*498*/		"			 int k0) {\n"
/*499*/		"	int k = get_global_id(0) + k0;\n"
/*500*/		"	int x, y, filtrok;\n"
/*501*/		"	KTensorRemap(k, x, y, filtrok, saidatx, saidaty)\n"
/*502*/		"	Ponto3d Kmapeado = {x * passox, y * passoy, 0};\n"
/*503*/		"	REAL sum = 0, f, v;\n"
/*504*/		"	for (int i = 0; i < fx; i++)\n"
/*505*/		"		for (int j = 0; j < fy; j++)\n"
/*506*/		"			for (int z = 0; z < fz; z++) {\n"
/*507*/		"				f = W[KTensorMap4D(i, j, z, filtrok, fx, fy, fz)];\n"
/*508*/		"				v = A[KTensorMap(Kmapeado.x + i * largx, Kmapeado.y + j * largy, z, entradatx, entradaty)];\n"
/*509*/		"\n"
/*510*/		"				sum += f * v;\n"
/*511*/		"			}\n"
/*512*/		"	Z[k] = sum;\n"
/*513*/		"	S[k] = func(fid, sum);\n"
/*514*/		"}\n"
/*515*/		"\n"
/*516*/		"kV convncCalcGradZ(Vector ds, Vector z, Vector dz, unsigned int fid, int k0) {\n"
/*517*/		"	int k = get_global_id(0) + k0;\n"
/*518*/		"	dz[k] = ds[k] * func(fid, z[k]);\n"
/*519*/		"}\n"
/*520*/		"\n"
/*521*/		"kV convncCalcGrads(Vector W,\n"
/*522*/		"				   Vector DA,\n"
/*523*/		"				   Vector dz,\n"
/*524*/		"				   unsigned int passox, unsigned int passoy,\n"
/*525*/		"				   unsigned int largx, unsigned int largy,\n"
/*526*/		"				   unsigned int entradatx, unsigned int entradaty,\n"
/*527*/		"				   unsigned int saidatx, unsigned int saidaty,\n"
/*528*/		"				   unsigned int fx, unsigned int fy, unsigned int fz,\n"
/*529*/		"				   int k0) {\n"
/*530*/		"	/**\n"
/*531*/		" * equacao a ser implementada \\n\n"
/*532*/		" * x = s*p + m*w \\n\n"
/*533*/		" * onde: \\n\n"
/*534*/		" * 	x é da entrada \\n\n"
/*535*/		" * 	s é da saida \\n\n"
/*536*/		" * 	m é do filtro\\n\n"
/*537*/		" * 	s = (x - m*w)/p \\n\n"
/*538*/		" */\n"
/*539*/		"	int k = get_global_id(0) + k0;\n"
/*540*/		"	int x, y, z;\n"
/*541*/		"	KTensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*542*/		"	Range range_filtro;\n"
/*543*/		"	range_filtro.min.x = 0;\n"
/*544*/		"	if ((entradatx - x - (fx - 1) * largx) < 0) {\n"
/*545*/		"		range_filtro.min.x = -entradatx + x + fx;\n"
/*546*/		"	}\n"
/*547*/		"	range_filtro.max.x = fx - 1;\n"
/*548*/		"	if (x - (fx - 1) * largx < 0) {\n"
/*549*/		"		range_filtro.max.x = x / largx;\n"
/*550*/		"	}\n"
/*551*/		"	range_filtro.min.y = 0;\n"
/*552*/		"	if ((entradaty - y - (fy - 1) * largy) < 0) {\n"
/*553*/		"		range_filtro.min.y = -entradaty + y + fy;\n"
/*554*/		"	}\n"
/*555*/		"	range_filtro.max.y = fy - 1;\n"
/*556*/		"	if (y - (fy - 1) * largy < 0) {\n"
/*557*/		"		range_filtro.max.y = y / largy;\n"
/*558*/		"	}\n"
/*559*/		"	int sx, sy;\n"
/*560*/		"	REAL somaErro = 0, aux, pesoAplicado = 0;\n"
/*561*/		"	for (int m = range_filtro.min.x; m <= range_filtro.max.x; m++) {\n"
/*562*/		"		sx = (x - m * largx) / passox;\n"
/*563*/		"		if (sx * passox + m * largx != x)continue;\n"
/*564*/		"		for (int n = range_filtro.min.y; n <= range_filtro.max.y; n++) {\n"
/*565*/		"			sy = (y - n * largy) / passox;\n"
/*566*/		"			if (sy * passoy + n * largy != y)continue;\n"
/*567*/		"			for (int l = 0; l < fz; l++) {\n"
/*568*/		"				pesoAplicado = W[KTensorMap4D(m, n, z, l, fx, fy, fz)];\n"
/*569*/		"				aux = pesoAplicado * dz[KTensorMap(sx, sy, l, saidatx, saidaty)];\n"
/*570*/		"				somaErro += aux;\n"
/*571*/		"			}\n"
/*572*/		"		}\n"
/*573*/		"	}\n"
/*574*/		"	DA[k] = somaErro;\n"
/*575*/		"}\n"
/*576*/		"\n"
/*577*/		"kV convncCalcFiltro(Vector dz,\n"
/*578*/		"					Vector A,\n"
/*579*/		"					Vector W,\n"
/*580*/		"					Vector dW,\n"
/*581*/		"					unsigned int dw_x, unsigned int dw_y, unsigned int dw_z,\n"
/*582*/		"					unsigned int a_x, unsigned int a_y,\n"
/*583*/		"					unsigned int s_x, unsigned int s_y,\n"
/*584*/		"					unsigned int passox, unsigned int passoy,\n"
/*585*/		"					unsigned int largx, unsigned int largy,\n"
/*586*/		"					REAL hitlearn, REAL momento, REAL weightDecay,\n"
/*587*/		"					int k0) {\n"
/*588*/		"	int k = get_global_id(0) + k0;\n"
/*589*/		"	int m, n, z, l;\n"
/*590*/		"	KTensorRemap4D(k, m, n, z, l, dw_x, dw_y, dw_z)\n"
/*591*/		"	REAL soma = 0, aux;\n"
/*592*/		"	for (int i = 0; i < s_x; ++i) {\n"
/*593*/		"		for (int j = 0; j < s_y; ++j) {\n"
/*594*/		"			aux = A[KTensorMap(i * passox + m * largx, j * passoy + n * largy, z, a_x, a_y)]\n"
/*595*/		"				  * dz[KTensorMap(i, j, l, s_x, s_y)];\n"
/*596*/		"			soma += aux;\n"
/*597*/		"		}\n"
/*598*/		"	}\n"
/*599*/		"	dW[k] = soma + dW[k] * momento;\n"
/*600*/		"	W[k] = W[k] - hitlearn * (dW[k] + W[k] * weightDecay);\n"
/*601*/		"\n"
/*602*/		"}\n"
/*603*/		"\n"
/*604*/		"\n"
/*605*/		"\n"
/*606*/		"\n"
/*607*/		"//dropout.h\n"
/*608*/		"#define MAX_INT_DP  ((1UL << 31) - 1)\n"
/*609*/		"long randoml(unsigned long seed,unsigned long id) {\n"
/*610*/		"	seed += id;\n"
/*611*/		"	return (seed * 0x5deece66dL + 0xbL) & MAX_INT_DP;\n"
/*612*/		"}\n"
/*613*/		"\n"
/*614*/		"REAL randomD(unsigned long seed,unsigned long id) {\n"
/*615*/		"	return (REAL) randoml(seed, id) / (REAL) MAX_INT_DP;\n"
/*616*/		"}\n"
/*617*/		"\n"
/*618*/		"kV dropativa(Vector entrada, Vector saida, __global char *hitmap, long seed,\n"
/*619*/		"			 REAL pativa, int k0) {\n"
/*620*/		"	int i = get_global_id(0) + k0;\n"
/*621*/		"//	printf(\"kernel %lf %lf %g %g\\n\",randomD(seed, i),pativa,(REAL)(seed +i),(REAL)MAX_INT_DP);\n"
/*622*/		"	char teste = (char) (randomD(seed, i) <= pativa);\n"
/*623*/		"	hitmap[i] = teste;\n"
/*624*/		"	saida[i] = teste * entrada[i];\n"
/*625*/		"}\n"
/*626*/		"\n"
/*627*/		"\n"
/*628*/		"kV dropcalcgrad(Vector gradentrada, __global char *hitmap, Vector gradnext, int k0) {\n"
/*629*/		"	int i = get_global_id(0) + k0;\n"
/*630*/		"	gradentrada[i] = hitmap[i] * gradnext[i];\n"
/*631*/		"}\n"
/*632*/		"\n"
/*633*/		"//fullconnect.h\n"
/*634*/		"\n"
/*635*/		"/**\n"
/*636*/		" *\n"
/*637*/		" * @param entrada (N,1,1)\n"
/*638*/		" * @param pesos (M,N,1)\n"
/*639*/		" * @param b (N,1,1)\n"
/*640*/		" * @param z (N,1,1)\n"
/*641*/		" * @param saida (N,1,1)\n"
/*642*/		" * @param funcaoativacao\n"
/*643*/		" * @param pesosx M\n"
/*644*/		" * @param pesosy N\n"
/*645*/		" * @param k0\n"
/*646*/		" */\n"
/*647*/		"kV fullfeed(Vector entrada, Vector pesos, Vector b, Vector z, Vector saida,\n"
/*648*/		"			int funcaoativacao, int pesosx, int pesosy, int k0) {\n"
/*649*/		"	int m = get_global_id(0) + k0;\n"
/*650*/		"	REAL valorEntrada = 0;\n"
/*651*/		"	int n;\n"
/*652*/		"	for (n = 0; n < pesosy; n++) {\n"
/*653*/		"		valorEntrada += entrada[n] * pesos[KTensorMap(m, n, 0, pesosx, pesosy)];\n"
/*654*/		"	}\n"
/*655*/		"	z[m] = valorEntrada + b[m];\n"
/*656*/		"	saida[m] = func(funcaoativacao, valorEntrada);\n"
/*657*/		"}\n"
/*658*/		"\n"
/*659*/		"kV fullCalcDWandFix(Vector a,\n"
/*660*/		"					Vector w,\n"
/*661*/		"					Vector dw,\n"
/*662*/		"					Vector dz,\n"
/*663*/		"					REAL hitlearn,\n"
/*664*/		"					REAL momento,\n"
/*665*/		"					REAL decaimentoDePeso,\n"
/*666*/		"					int pesosy,\n"
/*667*/		"					int k0) {\n"
/*668*/		"	int k = get_global_id(0) + k0;\n"
/*669*/		"	int m, n;\n"
/*670*/		"	m = k / pesosy;\n"
/*671*/		"	n = k % pesosy;\n"
/*672*/		"	dw[k] = dz[m] * a[n] + dw[k] * momento;\n"
/*673*/		"	w[k] = w[k] - hitlearn * (dw[k] + w[k] * decaimentoDePeso);\n"
/*674*/		"}\n"
/*675*/		"\n"
/*676*/		"kV fullCalcDz(Vector dz, Vector ds, Vector z, Vector b, Vector db,\n"
/*677*/		"			  int dfa, REAL hitlearn,\n"
/*678*/		"			  REAL momento, REAL decaimentoDePeso,\n"
/*679*/		"			  int k0) {\n"
/*680*/		"	int m = get_global_id(0) + k0;\n"
/*681*/		"	dz[m] = ds[m] * func(dfa, z[m]);\n"
/*682*/		"}\n"
/*683*/		"\n"
/*684*/		"kV fullCalcDzAndFixB(Vector dz, Vector ds, Vector z, Vector b,\n"
/*685*/		"					 Vector db, int dfa, REAL hitlearn,\n"
/*686*/		"					 REAL momento, REAL decaimentoDePeso,\n"
/*687*/		"					 int k0) {\n"
/*688*/		"	int m = get_global_id(0) + k0;\n"
/*689*/		"	dz[m] = ds[m] * func(dfa, z[m]);\n"
/*690*/		"	db[m] = dz[m] + db[m] * momento;\n"
/*691*/		"	b[m] = b[m] - hitlearn * (db[m] + b[m] * decaimentoDePeso);\n"
/*692*/		"}\n"
/*693*/		"\n"
/*694*/		"kV fullcalcin(Vector dz, Vector da, Vector w, int pesosx, int pesosy,\n"
/*695*/		"			  int k0) {\n"
/*696*/		"	int m = get_global_id(0) + k0;\n"
/*697*/		"	REAL soma = 0;\n"
/*698*/		"	for (int n = 0; n < pesosx; ++n) {\n"
/*699*/		"		soma += dz[n] * w[KTensorMap(n, m, 0, pesosx, pesosy)];\n"
/*700*/		"	}\n"
/*701*/		"	da[m] = soma;\n"
/*702*/		"}\n"
/*703*/		"\n"
/*704*/		"//padding.h\n"
/*705*/		"\n"
/*706*/		"kV paddingfeed(Vector in,Vector out,\n"
/*707*/		"			   unsigned int txi,unsigned int tyi,\n"
/*708*/		"			   unsigned int txo,unsigned int tyo,\n"
/*709*/		"			   unsigned int t, unsigned int l ,\n"
/*710*/		"			   int k0){\n"
/*711*/		"	int k = get_global_id(0) + k0;\n"
/*712*/		"	int x, y, z;\n"
/*713*/		"	KTensorRemap(k, x, y, z, txi, tyi)\n"
/*714*/		"	int s = KTensorMap(x+t,y+l,z,txo,tyo);\n"
/*715*/		"	out[s] = in[k];\n"
/*716*/		"}\n"
/*717*/		"kV paddingBack(Vector gradNext,Vector gradin,\n"
/*718*/		"			   unsigned int txi, unsigned int tyi,\n"
/*719*/		"			   unsigned int txo,unsigned int tyo,\n"
/*720*/		"			   unsigned int t, unsigned int l , int k0){\n"
/*721*/		"	int k = get_global_id(0) + k0;\n"
/*722*/		"	int x, y, z;\n"
/*723*/		"	KTensorRemap(k, x, y, z, txi, tyi)\n"
/*724*/		"	int s = KTensorMap(x+t,y+l,z,txo,tyo);\n"
/*725*/		"	gradin[k] = gradNext[s];\n"
/*726*/		"}\n"
/*727*/		"//poolav.h\n"
/*728*/		"kV poolAVativa(Vector entrada, Vector saida,\n"
/*729*/		"			   int passox, int passoy,\n"
/*730*/		"			   int fx, int fy,\n"
/*731*/		"			   int saidatx, int saidaty, int entradatx, int entradaty, int k0) {\n"
/*732*/		"	int k = get_global_id(0) + k0;\n"
/*733*/		"	int x, y, z;\n"
/*734*/		"	KTensorRemap(k, x, y, z, saidatx, saidaty)\n"
/*735*/		"\n"
/*736*/		"	Ponto3d mapeado = {x * passox, y * passoy, 0};\n"
/*737*/		"	REAL soma = 0;\n"
/*738*/		"\n"
/*739*/		"	for (int i = 0; i < fx; ++i) {\n"
/*740*/		"		for (int j = 0; j < fy; ++j) {\n"
/*741*/		"			soma += entrada[KTensorMap(mapeado.x + i, mapeado.y + j, z, entradatx, entradaty)];\n"
/*742*/		"		}\n"
/*743*/		"	}\n"
/*744*/		"	saida[k] = soma / (fx * fy);\n"
/*745*/		"}\n"
/*746*/		"\n"
/*747*/		"\n"
/*748*/		"kV poolAvCalcGrads(Vector entrada, Vector gradEntrada, Vector gradNext, Vector saida,\n"
/*749*/		"				   int fx, int fy, int px, int py,\n"
/*750*/		"				   int entradatx, int entradaty,\n"
/*751*/		"				   int saidatx, int saidaty,\n"
/*752*/		"				   int k0) {\n"
/*753*/		"	int k = get_global_id(0) + k0;\n"
/*754*/		"	int x, y, z;\n"
/*755*/		"	KTensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*756*/		"	Range range_filtro;\n"
/*757*/		"	range_filtro.min.x = 0;\n"
/*758*/		"	if (x + fx > entradatx) {\n"
/*759*/		"		range_filtro.min.x = x + fx - entradatx;\n"
/*760*/		"	}\n"
/*761*/		"	range_filtro.max.x = fx - 1;\n"
/*762*/		"	if (x - fx + 1 < 0) {\n"
/*763*/		"		range_filtro.max.x = x;\n"
/*764*/		"	}\n"
/*765*/		"	range_filtro.min.y = 0;\n"
/*766*/		"	if (y + fy > entradaty) {\n"
/*767*/		"		range_filtro.min.y = y + fy - entradaty;\n"
/*768*/		"	}\n"
/*769*/		"	range_filtro.max.y = fy - 1;\n"
/*770*/		"	if (y - fy + 1 < 0) {\n"
/*771*/		"		range_filtro.max.y = y;\n"
/*772*/		"	}\n"
/*773*/		"	int i, j;//saida\n"
/*774*/		"	REAL soma = 0;\n"
/*775*/		"	for (int m = range_filtro.min.x; m <= range_filtro.max.x; m++) {\n"
/*776*/		"		i = (x - m) / px;\n"
/*777*/		"		if (i * px + m != x)continue;\n"
/*778*/		"		for (int n = range_filtro.min.y; n <= range_filtro.max.y; n++) {\n"
/*779*/		"			j = (y - n) / py;\n"
/*780*/		"			if (j * py + n != y)continue;\n"
/*781*/		"			soma += gradNext[KTensorMap(i, j, z, saidatx, saidaty)];\n"
/*782*/		"		}\n"
/*783*/		"	}\n"
/*784*/		"	gradEntrada[KTensorMap(x, y, z, entradatx, entradaty)] = soma / (fx * fy);\n"
/*785*/		"\n"
/*786*/		"}\n"
/*787*/		"\n"
/*788*/		"\n"
/*789*/		"//poolMax.h\n"
/*790*/		"kV poolativa(Vector entrada, Vector saida,\n"
/*791*/		"			 int passox, int passoy,\n"
/*792*/		"			 int filtrox, int filtroy,\n"
/*793*/		"			 int saidatx, int saidaty,\n"
/*794*/		"			 int entradatx, int entradaty, int k0) {\n"
/*795*/		"	int k = get_global_id(0) + k0;\n"
/*796*/		"	int x, y, z;\n"
/*797*/		"	KTensorRemap(k, x, y, z, saidatx, saidaty)\n"
/*798*/		"\n"
/*799*/		"	Ponto3d mapeado = {x * passox, y * passoy, 0};\n"
/*800*/		"	REAL mval, v;\n"
/*801*/		"	mval = -DBL_MAX;\n"
/*802*/		"	for (int i = 0; i < filtrox; ++i) {\n"
/*803*/		"		for (int j = 0; j < filtroy; ++j) {\n"
/*804*/		"			v = entrada[KTensorMap(mapeado.x + i, mapeado.y + j, z, entradatx, entradaty)];\n"
/*805*/		"			if (v > mval)\n"
/*806*/		"				mval = v;\n"
/*807*/		"		}\n"
/*808*/		"	}\n"
/*809*/		"	saida[k] = mval;\n"
/*810*/		"}\n"
/*811*/		"\n"
/*812*/		"\n"
/*813*/		"kV poolCalcGrads(Vector entrada, Vector gradEntrada,\n"
/*814*/		"				 Vector gradNext, Vector saida,\n"
/*815*/		"				 int fx, int fy, int px, int py,\n"
/*816*/		"				 int entradatx, int entradaty,\n"
/*817*/		"				 int saidatx, int saidaty,\n"
/*818*/		"				 int k0) {\n"
/*819*/		"	int k = get_global_id(0) + k0;\n"
/*820*/		"	int x, y, z;\n"
/*821*/		"	KTensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*822*/		"	Range range_filtro;\n"
/*823*/		"	if (x + fx > entradatx) {\n"
/*824*/		"		range_filtro.min.x = x + fx - entradatx;\n"
/*825*/		"	}\n"
/*826*/		"	range_filtro.max.x = fx - 1;\n"
/*827*/		"	if (x - fx + 1 < 0) {\n"
/*828*/		"		range_filtro.max.x = x;\n"
/*829*/		"	}\n"
/*830*/		"	range_filtro.min.y = 0;\n"
/*831*/		"	if (y + fy > entradaty) {\n"
/*832*/		"		range_filtro.min.y = y + fy - entradaty;\n"
/*833*/		"	}\n"
/*834*/		"	range_filtro.max.y = fy - 1;\n"
/*835*/		"	if (y - fy + 1 < 0) {\n"
/*836*/		"		range_filtro.max.y = y;\n"
/*837*/		"	}\n"
/*838*/		"	int i, j;//saida\n"
/*839*/		"	gradEntrada[KTensorMap(x, y, z, entradatx, entradaty)] = 0;\n"
/*840*/		"	for (int m = range_filtro.min.x; m <= range_filtro.max.x; m++) {\n"
/*841*/		"		i = (x - m) / px;\n"
/*842*/		"		if (i * px + m != x)continue;\n"
/*843*/		"		for (int n = range_filtro.min.y; n <= range_filtro.max.y; n++) {\n"
/*844*/		"			j = (y - n) / py;\n"
/*845*/		"			if (j * py + n != y)continue;\n"
/*846*/		"			if (entrada[k] == saida[KTensorMap(i, j, z, saidatx, saidaty)]) {\n"
/*847*/		"				gradEntrada[k] = gradNext[KTensorMap(i, j, z, saidatx, saidaty)];\n"
/*848*/		"				return;\n"
/*849*/		"			}\n"
/*850*/		"		}\n"
/*851*/		"	}\n"
/*852*/		"\n"
/*853*/		"}\n"
/*854*/		"\n"
/*855*/		"\n"
/*856*/		"//poolMin.h\n"
/*857*/		"kV poolativaMin(Vector entrada, Vector saida,\n"
/*858*/		"				int passox, int passoy,\n"
/*859*/		"				int filtrox, int filtroy,\n"
/*860*/		"				int saidatx, int saidaty,\n"
/*861*/		"				int entradatx, int entradaty, int k0) {\n"
/*862*/		"	int k = get_global_id(0) + k0;\n"
/*863*/		"	int x, y, z;\n"
/*864*/		"	KTensorRemap(k, x, y, z, saidatx, saidaty)\n"
/*865*/		"\n"
/*866*/		"	Ponto3d mapeado = {x * passox, y * passoy, 0};\n"
/*867*/		"	REAL mval, v;\n"
/*868*/		"	mval = DBL_MAX;\n"
/*869*/		"	for (int i = 0; i < filtrox; ++i) {\n"
/*870*/		"		for (int j = 0; j < filtroy; ++j) {\n"
/*871*/		"			v = entrada[KTensorMap(mapeado.x + i, mapeado.y + j, z, entradatx, entradaty)];\n"
/*872*/		"			if (v < mval)\n"
/*873*/		"				mval = v;\n"
/*874*/		"		}\n"
/*875*/		"	}\n"
/*876*/		"	saida[k] = mval;\n"
/*877*/		"}\n"
/*878*/		"\n"
/*879*/		"\n"
/*880*/		"//prelu.h\n"
/*881*/		"kV preluativa(Vector entrada, Vector saida, Vector A, int k0) {\n"
/*882*/		"	int k = get_global_id(0) + k0;\n"
/*883*/		"	REAL v = entrada[k];\n"
/*884*/		"	if (v < 0)\n"
/*885*/		"		v = v * A[k];\n"
/*886*/		"	saida[k] = v;\n"
/*887*/		"}\n"
/*888*/		"\n"
/*889*/		"kV prelucalcgrad(Vector gradentrada, Vector entrada, Vector gradnext, Vector A, Vector dA,\n"
/*890*/		"				 int learn, REAL hitlearn, REAL momento,\n"
/*891*/		"				 REAL decaimento,\n"
/*892*/		"				 int k0) {\n"
/*893*/		"	int k = get_global_id(0) + k0;\n"
/*894*/		"	REAL v = entrada[k];\n"
/*895*/		"	if (v < 0) {\n"
/*896*/		"		gradentrada[k] = gradnext[k] * A[k];\n"
/*897*/		"		dA[k] = gradnext[k] + momento * dA[k];\n"
/*898*/		"	} else {\n"
/*899*/		"		gradentrada[k] = gradnext[k];\n"
/*900*/		"		dA[k] = momento * dA[k];\n"
/*901*/		"	}\n"
/*902*/		"	if (learn)\n"
/*903*/		"		A[k] = A[k] - hitlearn * (dA[k] + A[k] * decaimento);\n"
/*904*/		"}\n"
/*905*/		"\n"
/*906*/		"kV preluonlyfix(Vector entrada, Vector gradnext, Vector A, Vector dA,\n"
/*907*/		"				REAL hitlearn, REAL momento,\n"
/*908*/		"				REAL decaimento,\n"
/*909*/		"				int k0) {\n"
/*910*/		"	int k = get_global_id(0) + k0;\n"
/*911*/		"	REAL v = entrada[k];\n"
/*912*/		"	if (v < 0) {\n"
/*913*/		"		dA[k] = gradnext[k] + momento * dA[k];\n"
/*914*/		"	} else {\n"
/*915*/		"		dA[k] = momento * dA[k];\n"
/*916*/		"	}\n"
/*917*/		"	A[k] = A[k] - hitlearn * (dA[k] + A[k] * decaimento);\n"
/*918*/		"}\n"
/*919*/		"\n"
/*920*/		"//relu.h\n"
/*921*/		"\n"
/*922*/		"kV reluativa(Vector entrada, Vector saida, REAL menor, REAL maior, int k0) {\n"
/*923*/		"	int k = get_global_id(0) + k0;\n"
/*924*/		"	saida[k] = entrada[k] < 0.0 ? (entrada[k] * menor) : (entrada[k] * maior);\n"
/*925*/		"}\n"
/*926*/		"\n"
/*927*/		"\n"
/*928*/		"kV relucalcgrad(Vector gradentrada, Vector entrada, Vector gradnext, REAL menor, REAL maior, int k0) {\n"
/*929*/		"	int k = get_global_id(0) + k0;\n"
/*930*/		"	gradentrada[k] = entrada[k] < 0.0 ? (menor * gradnext[k]) : (maior * gradnext[k]);\n"
/*931*/		"}\n"
/*932*/		"\n"
/*933*/		"//softmax.h\n"
/*934*/		"/**\n"
/*935*/		" * @goal calcular e^a(x,y,z)\n"
/*936*/		" * @iteration dimensão de a (x,y,z)\n"
/*937*/		" * @param entrada Tensor de entrada (leitura)\n"
/*938*/		" * @param exponent Tensor e^entrada (escrita)\n"
/*939*/		" * @param k0 usado internamente no kernel\n"
/*940*/		" */\n"
/*941*/		"kV softmaxExp(Vector entrada, Vector exponent,int k0) {\n"
/*942*/		"	int k = get_global_id(0) + k0;\n"
/*943*/		"	exponent[k] = EXP(entrada[k]);\n"
/*944*/		"}\n"
/*945*/		"\n"
/*946*/		"\n"
/*947*/		"/***\n"
/*948*/		" * @goal encontrar a soma de cada dimensão z\n"
/*949*/		" * @iteration dimensão z da entrada a(:,:,z)\n"
/*950*/		" * @param eps Tensor exponencial da entrada (leitura)\n"
/*951*/		" * @param soma Tensor da soma das exponenciais (escrita)\n"
/*952*/		" * @param saidatx dimensão x da saída\n"
/*953*/		" * @param saidaty dimensão x da saída\n"
/*954*/		" * @param k0 usado internamente no kernel\n"
/*955*/		" */\n"
/*956*/		"kV softmaxSomaExp(Vector eps, Vector soma, int saidatx, int saidaty, int k0) {\n"
/*957*/		"	int z = get_global_id(0) + k0;\n"
/*958*/		"	int x, y;\n"
/*959*/		"	REAL sum = 0;\n"
/*960*/		"	for (x = 0; x < saidatx; x++)\n"
/*961*/		"		for (y = 0; y < saidaty; y++) {\n"
/*962*/		"			sum += eps[KTensorMap(x, y, z, saidatx, saidaty)];\n"
/*963*/		"		}\n"
/*964*/		"	soma[z] = sum;\n"
/*965*/		"}\n"
/*966*/		"/***\n"
/*967*/		" * @goal Normalizar a exponencial pela soma\n"
/*968*/		" *  * @iteration dimensão da saída  s(x,y,z)\n"
/*969*/		" * @param exponet Tensor exponencial da entrada (leitura)\n"
/*970*/		" * @param soma Tensor da soma das exponenciais (leitura)\n"
/*971*/		" * @param saida Tensor de saída (escrita)\n"
/*972*/		" * @param saidatx dimensão x da saída\n"
/*973*/		" * @param saidaty dimensão x da saída\n"
/*974*/		" * @param k0 usado internamente no kernel\n"
/*975*/		" */\n"
/*976*/		"kV softmaxNormaliza(Vector exponet, Vector soma, Vector saida,int saidatx, int saidaty, int k0) {\n"
/*977*/		"	int k = get_global_id(0) + k0;\n"
/*978*/		"	int x, y, z;\n"
/*979*/		"	KTensorRemap(k, x, y, z, saidatx, saidaty)\n"
/*980*/		"	saida[k] = exponet[k] / soma[z];\n"
/*981*/		"}\n"
/*982*/		"/**\n"
/*983*/		" * @goal Calcular os gradientes de entrada\n"
/*984*/		" * @iteration dimensão da entrada a(x,y,z)\n"
/*985*/		" * @param gradentrada Tensor de gradientes de entrada (escrita)\n"
/*986*/		" * @param entrada Tensor de entrada (leitura)\n"
/*987*/		" * @param gradnext Tensor gradiente da saída (leitura)\n"
/*988*/		" * @param k0 usado internamente no kernel\n"
/*989*/		" */\n"
/*990*/		"kV softMaxcalcgrad(Vector gradentrada, Vector entrada, Vector gradnext, int k0) {\n"
/*991*/		"	int k = get_global_id(0) + k0;\n"
/*992*/		"	REAL xi = entrada[k];\n"
/*993*/		"	gradentrada[k] = xi * (1.0 - xi) * gradnext[k];\n"
/*994*/		"}\n"
/*995*/		"\n"
/*996*/		"\n"
/*997*/		"#endif //GAB_KERNELS_OPENCL_H\n"
;
const char *getInternalDefaultKernel() {
	return __default_kernel__;
}