//
// Created by hslhe on 14/08/2021.
//
#include "utils/defaultkernel.h"
const char __default_kernel__[] = 
/*1*/		"#ifndef GAB_KERNELS_OPENCL_H\n"
/*2*/		"#define GAB_KERNELS_OPENCL_H\n"
/*3*/		"//utils.h\n"
/*4*/		"// Created by Xx220xX on 10/05/2020.\n"
/*5*/		"\n"
/*6*/		"#define Vector __global double *\n"
/*7*/		"\n"
/*8*/		"#define kV __kernel void\n"
/*9*/		"\n"
/*10*/		"#define TensorMap(x, y, z, tx, ty)((z)*(ty*tx)+(x)*ty+(y))\n"
/*11*/		"\n"
/*12*/		"#define TensorMap4D(x, y, z, l, tx, ty, tz)((l)*(ty)*(tx)*(tz)+(z)*(ty*tx)+(x)*ty+(y))\n"
/*13*/		"\n"
/*14*/		"#define TensorRemap4D(total, _x_, _y_, _z_, _l_, tx, ty, tz)\\\n"
/*15*/		"_y_ = total%ty      ;                                        \\\n"
/*16*/		"_x_ = (total - _y_)%(ty*tx)/ty ;                             \\\n"
/*17*/		"_z_ = (total- _x_*ty - _y_)%(tx*ty*tz)/(ty*tx)  ;            \\\n"
/*18*/		"_l_ = (total -_z_*tx*ty -_x_*ty - _y_)/(tx*ty*tz);\n"
/*19*/		"\n"
/*20*/		"\n"
/*21*/		"#define TensorRemap(total, _x_, _y_, _z_, tx, ty)\\\n"
/*22*/		"_y_ = total % ty;\\\n"
/*23*/		"_x_ = ((total - _y_) % (ty * tx)) / ty;\\\n"
/*24*/		"_z_ = (k - _x_ * ty - _y_) / (tx * ty);\n"
/*25*/		"\n"
/*26*/		"#define TensorRemap2D(total, x, y, ty)\\\n"
/*27*/		"y = total % ty;\\\n"
/*28*/		"x = total/ ty;\n"
/*29*/		"\n"
/*30*/		"typedef struct {\n"
/*31*/		"	int x, y, z;\n"
/*32*/		"} Ponto3d;\n"
/*33*/		"\n"
/*34*/		"typedef struct {\n"
/*35*/		"	Ponto3d min, max;\n"
/*36*/		"} Range;\n"
/*37*/		"\n"
/*38*/		"//bathnorm.h\n"
/*39*/		"\n"
/*40*/		"// achar a media\n"
/*41*/		"kV BatchNormMedia(Vector entrada, Vector media,\n"
/*42*/		"                  int entradatx, int entradaty, int k0) {\n"
/*43*/		"	int z = get_global_id(0) + k0;\n"
/*44*/		"	int x, y;\n"
/*45*/		"	double m = 0;\n"
/*46*/		"	for (x = 0; x < entradatx; x++) {\n"
/*47*/		"		for (y = 0; y < entradaty; y++) {\n"
/*48*/		"			m += entrada[TensorMap(x, y, z, entradatx, entradaty)];\n"
/*49*/		"		}\n"
/*50*/		"	}\n"
/*51*/		"	media[z] = m / (double) (entradatx * entradaty);\n"
/*52*/		"}\n"
/*53*/		"\n"
/*54*/		"// achar a diferenca\n"
/*55*/		"kV BatchNormDiferenca(Vector entrada, Vector media,\n"
/*56*/		"                      Vector diferenca,\n"
/*57*/		"                      Vector diferencaquad,\n"
/*58*/		"                      int entradatx, int entradaty, int k0) {\n"
/*59*/		"	int x, y, z;\n"
/*60*/		"	int k = get_global_id(0) + k0;\n"
/*61*/		"	TensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*62*/		"	diferenca[k] = entrada[k] - media[z];\n"
/*63*/		"	diferencaquad[k] = diferenca[k] * diferenca[k];\n"
/*64*/		"}\n"
/*65*/		"\n"
/*66*/		"kV BatchNormVariance(Vector dif, Vector difQuad,\n"
/*67*/		"                     Vector sumdiferenca, Vector variancia,\n"
/*68*/		"                     double episolon, int diftx, int difty,\n"
/*69*/		"                     int k0) {\n"
/*70*/		"	int z = get_global_id(0) + k0;\n"
/*71*/		"	double sum = 0;\n"
/*72*/		"	double sumdif = 0;\n"
/*73*/		"	for (int x = 0; x < diftx; x++) {\n"
/*74*/		"		for (int y = 0; y < difty; y++) {\n"
/*75*/		"			sum += difQuad[TensorMap(x, y, z, diftx, difty)];\n"
/*76*/		"			sumdif += dif[TensorMap(x, y, z, diftx, difty)];\n"
/*77*/		"		}\n"
/*78*/		"	}\n"
/*79*/		"	sumdiferenca[z] = sumdif;\n"
/*80*/		"	variancia[z] = sqrt(sum / (difty * diftx) + episolon);\n"
/*81*/		"}\n"
/*82*/		"\n"
/*83*/		"// normaliza\n"
/*84*/		"kV BatchNormNormaliza(Vector saida,\n"
/*85*/		"                      Vector norma,\n"
/*86*/		"                      Vector diferenca,\n"
/*87*/		"                      Vector variancia,\n"
/*88*/		"                      Vector Y,\n"
/*89*/		"                      Vector B,\n"
/*90*/		"                      int diferencatx, int diferencaty, int k0) {\n"
/*91*/		"	int x, y, z;\n"
/*92*/		"	int k = get_global_id(0) + k0;\n"
/*93*/		"	TensorRemap(k, x, y, z, diferencatx, diferencaty)\n"
/*94*/		"	norma[k] = diferenca[k] / variancia[z];\n"
/*95*/		"	saida[k] = norma[k] * Y[z] + B[z];\n"
/*96*/		"}\n"
/*97*/		"\n"
/*98*/		"\n"
/*99*/		"kV BatchNormaCalcGrad1(Vector gradIn,\n"
/*100*/		"                       Vector gradNext,\n"
/*101*/		"                       Vector variancia,\n"
/*102*/		"                       Vector media,\n"
/*103*/		"                       Vector Y,\n"
/*104*/		"\n"
/*105*/		"                       Vector somaDif,\n"
/*106*/		"                       Vector entrada,\n"
/*107*/		"                       int entradatx,\n"
/*108*/		"                       int entradaty,\n"
/*109*/		"                       int k0) {\n"
/*110*/		"	int x, y, z;\n"
/*111*/		"	int k = get_global_id(0) + k0;\n"
/*112*/		"	TensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*113*/		"	double M = entradatx * entradaty;\n"
/*114*/		"	double dif_variance = somaDif[z] - entrada[k] + media[z] + (entrada[k] - media[z]) * (M - 1);\n"
/*115*/		"	dif_variance = dif_variance * -1.0 / (variancia[z] * M * M);\n"
/*116*/		"\n"
/*117*/		"	double didx = variancia[z] * (M - 1 / M) + (media[z] - entrada[k]) * dif_variance;\n"
/*118*/		"	didx = didx / (variancia[z] * variancia[z]);\n"
/*119*/		"	didx = didx * gradNext[k];\n"
/*120*/		"	gradIn[k] = didx * Y[z];\n"
/*121*/		"}\n"
/*122*/		"\n"
/*123*/		"kV BatchNormaCalcGrad2(Vector gradNext,\n"
/*124*/		"                       Vector norma,\n"
/*125*/		"                       Vector gradY,\n"
/*126*/		"                       Vector gradB,\n"
/*127*/		"                       int entradatx,\n"
/*128*/		"                       int entradaty,\n"
/*129*/		"                       int k0) {\n"
/*130*/		"	int z = get_global_id(0) + k0;\n"
/*131*/		"	double sumY = 0;\n"
/*132*/		"	double sumB = 0;\n"
/*133*/		"	int k;\n"
/*134*/		"	for (int x = 0; x < entradatx; ++x) {\n"
/*135*/		"		for (int y = 0; y < entradaty; ++y) {\n"
/*136*/		"			k = TensorMap(x, y, z, entradatx, entradaty);\n"
/*137*/		"			sumY += gradNext[k];\n"
/*138*/		"			sumB += gradNext[k] * norma[k];\n"
/*139*/		"		}\n"
/*140*/		"	}\n"
/*141*/		"	gradB[z] = sumB;\n"
/*142*/		"	gradY[z] = sumY;\n"
/*143*/		"}\n"
/*144*/		"\n"
/*145*/		"\n"
/*146*/		"kV batchNormCorrigePeso(Vector gradY,\n"
/*147*/		"                        Vector gradB,\n"
/*148*/		"                        Vector Y,\n"
/*149*/		"                        Vector B,\n"
/*150*/		"                        double hitlearn,\n"
/*151*/		"                        int k0) {\n"
/*152*/		"	int z = get_global_id(0) + k0;\n"
/*153*/		"	B[z] = B[z] - gradB[z] * hitlearn;\n"
/*154*/		"	Y[z] = Y[z] - gradY[z] * hitlearn;\n"
/*155*/		"}\n"
/*156*/		"//cnnutils.h\n"
/*157*/		"//\n"
/*158*/		"// Created by Henrique on 22-Jul-21.\n"
/*159*/		"//\n"
/*160*/		"\n"
/*161*/		"\n"
/*162*/		"kV createImg(__global unsigned char *out, Vector v, int vx, int vy, int imi, int imy, int k0) {\n"
/*163*/		"	int k = get_global_id(0) + k0;\n"
/*164*/		"	int i, j, z;\n"
/*165*/		"	TensorRemap(k, i, j, z, vx, vy)\n"
/*166*/		"	imi = imi + i;\n"
/*167*/		"	int imj = j + z * vy + z;\n"
/*168*/		"	out[imi * imy + imj] = ((int) v[k]) & 0xff;\n"
/*169*/		"}\n"
/*170*/		"\n"
/*171*/		"\n"
/*172*/		"kV\n"
/*173*/		"normalizeVector(Vector input, Vector saida, double multiplicador, double somador, double subtrator,\n"
/*174*/		"				int k0) {\n"
/*175*/		"	int k = get_global_id(0) + k0;\n"
/*176*/		"	saida[k] = (input[k] + somador) * multiplicador - subtrator;\n"
/*177*/		"}\n"
/*178*/		"\n"
/*179*/		"\n"
/*180*/		"kV subKernel(Vector grad, Vector saida, Vector target, int k0) {\n"
/*181*/		"	int k = get_global_id(0) + k0;\n"
/*182*/		"	grad[k] = saida[k] - target[k];\n"
/*183*/		"}\n"
/*184*/		"\n"
/*185*/		"kV divKernel(Vector v, double value, int k0) {\n"
/*186*/		"	int k = get_global_id(0) + k0;\n"
/*187*/		"	v[k] = v[k] / value;\n"
/*188*/		"}\n"
/*189*/		"\n"
/*190*/		"kV divIntDo(__global unsigned char *src, Vector v, double value, int k0) {\n"
/*191*/		"	int k = get_global_id(0) + k0;\n"
/*192*/		"	v[k] = ((double) src[k]) / value;\n"
/*193*/		"}\n"
/*194*/		"\n"
/*195*/		"kV int2vector(__global unsigned char *ints, Vector v, int noptiobs, int k0) {\n"
/*196*/		"//	int k = get_global_id(0) + k0;\n"
/*197*/		"//\n"
/*198*/		"//	int d;\n"
/*199*/		"//	for (int j = 0; j < noptiobs; j++) {\n"
/*200*/		"//		d = TensorMap4D(0, j, 0, k, 1, noptiobs, 1);\n"
/*201*/		"//		v[d] = (double) (j == ints[k]);\n"
/*202*/		"//	}\n"
/*203*/		"	int k = get_global_id(0) + k0;\n"
/*204*/		"	int x,y,z,w;\n"
/*205*/		"	TensorRemap4D(k,x,y,z,w,1,noptiobs,1);\n"
/*206*/		"	v[k] = (double) (y == ints[w]);\n"
/*207*/		"}\n"
/*208*/		"\n"
/*209*/		"\n"
/*210*/		"\n"
/*211*/		"\n"
/*212*/		"//conv.h\n"
/*213*/		"kV convSum(Vector filtro, Vector entrada, Vector saida,\n"
/*214*/		"           int passox, int passoy,\n"
/*215*/		"           int saidatx, int saidaty,\n"
/*216*/		"           int entradatx, int entradaty,\n"
/*217*/		"           int fx, int fy, int fz, int k0) {\n"
/*218*/		"	int k = get_global_id(0) + k0;\n"
/*219*/		"	int x, y, filtrok;\n"
/*220*/		"	TensorRemap(k, x, y, filtrok, saidatx, saidaty)\n"
/*221*/		"	double sum = 0, f = 0, v = 0;\n"
/*222*/		"	int lf = 0, le = 0;\n"
/*223*/		"	for (int m = 0; m < fx; m++) {\n"
/*224*/		"		for (int n = 0; n < fy; n++) {\n"
/*225*/		"			for (int z = 0; z < fz; z++) {\n"
/*226*/		"				lf = TensorMap4D(m, n, z, filtrok, fx, fy, fz);\n"
/*227*/		"				le = TensorMap(x * passox + m, y * passoy + n, z, entradatx, entradaty);\n"
/*228*/		"				f = filtro[lf];\n"
/*229*/		"				v = entrada[le];\n"
/*230*/		"				sum += f * v;\n"
/*231*/		"			}\n"
/*232*/		"		}\n"
/*233*/		"	}\n"
/*234*/		"	saida[k] = sum;\n"
/*235*/		"}\n"
/*236*/		"\n"
/*237*/		"\n"
/*238*/		"kV convCalcGradAndFixWeight(Vector filtros, Vector ds,\n"
/*239*/		"                            Vector entrada, Vector gradFiltro,\n"
/*240*/		"                            int fx, int fy, int fz,\n"
/*241*/		"                            int entrada_tx, int entrada_ty,\n"
/*242*/		"                            int saida_tx, int saida_ty,\n"
/*243*/		"                            int passox, int passoy,\n"
/*244*/		"                            double hitLearn, double momento, double weightDecay,\n"
/*245*/		"                            int k0) {\n"
/*246*/		"	int k = get_global_id(0) + k0;\n"
/*247*/		"	int m, n, z, l;\n"
/*248*/		"	TensorRemap4D(k, m, n, z, l, fx, fy, fz)\n"
/*249*/		"	double soma = 0;\n"
/*250*/		"	int le, ls;\n"
/*251*/		"	for (int i = 0; i < saida_tx; ++i) {\n"
/*252*/		"		for (int j = 0; j < saida_ty; ++j) {\n"
/*253*/		"			le = TensorMap(i * passox + m, j * passoy + n, z, entrada_tx, entrada_ty);\n"
/*254*/		"			ls = TensorMap(i, j, l, saida_tx, saida_ty);\n"
/*255*/		"			soma += entrada[le]\n"
/*256*/		"			        * ds[ls];\n"
/*257*/		"		}\n"
/*258*/		"	}\n"
/*259*/		"	double dw = soma + gradFiltro[k] * momento;\n"
/*260*/		"	double w = filtros[k];\n"
/*261*/		"	filtros[k] = w - hitLearn * (dw + w * weightDecay);\n"
/*262*/		"	gradFiltro[k] = dw;\n"
/*263*/		"}\n"
/*264*/		"\n"
/*265*/		"kV convCalcGradIn(Vector filtro, Vector gradEntrada, Vector gradNext,\n"
/*266*/		"                  int fx, int fy, int fz,\n"
/*267*/		"                  int passox, int passoy,\n"
/*268*/		"                  int entradatx, int entradaty,\n"
/*269*/		"                  int saidatx, int saidaty, int saidatz,\n"
/*270*/		"                  int k0) {\n"
/*271*/		"	int k = get_global_id(0) + k0;\n"
/*272*/		"	int x, y, z;\n"
/*273*/		"	TensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*274*/		"\n"
/*275*/		"	Range range_filtro;\n"
/*276*/		"	range_filtro.min.x = 0;\n"
/*277*/		"	if (x + fx > entradatx) {\n"
/*278*/		"		range_filtro.min.x = x + fx - entradatx;\n"
/*279*/		"	}\n"
/*280*/		"	range_filtro.max.x = fx - 1;\n"
/*281*/		"	if (x - fx + 1 < 0) {\n"
/*282*/		"		range_filtro.max.x = x;\n"
/*283*/		"	}\n"
/*284*/		"	range_filtro.min.y = 0;\n"
/*285*/		"	if (y + fy > entradaty) {\n"
/*286*/		"		range_filtro.min.y = y + fy - entradaty;\n"
/*287*/		"	}\n"
/*288*/		"	range_filtro.max.y = fy - 1;\n"
/*289*/		"	if (y - fy + 1 < 0) {\n"
/*290*/		"		range_filtro.max.y = y;\n"
/*291*/		"	}\n"
/*292*/		"	double somaErro = 0, pesoAplicado = 0;\n"
/*293*/		"	int i, j;\n"
/*294*/		"	int lf, ls;\n"
/*295*/		"	for (int m = range_filtro.min.x; m <= range_filtro.max.x; m++) {\n"
/*296*/		"		i = (x - m) / passox;\n"
/*297*/		"		if (i * passox + m != x) continue;\n"
/*298*/		"		for (int n = range_filtro.min.y; n <= range_filtro.max.y; n++) {\n"
/*299*/		"			j = (y - n) / passoy;\n"
/*300*/		"			if (j * passoy + n != y) continue;\n"
/*301*/		"			for (int w = 0; w < saidatz; w++) {\n"
/*302*/		"				lf = TensorMap4D(m, n, z, w, fx, fy, fz);\n"
/*303*/		"				ls = TensorMap(i, j, w, saidatx, saidaty);\n"
/*304*/		"				pesoAplicado = filtro[lf];\n"
/*305*/		"				somaErro += pesoAplicado * gradNext[ls];\n"
/*306*/		"			}\n"
/*307*/		"		}\n"
/*308*/		"	}\n"
/*309*/		"	gradEntrada[k] = somaErro;\n"
/*310*/		"}\n"
/*311*/		"\n"
/*312*/		"\n"
/*313*/		"//convNc.h\n"
/*314*/		"//#include\"utils.h\"\n"
/*315*/		"kV convncSum(Vector filtro, Vector entrada, Vector saida,\n"
/*316*/		"             int passox, int passoy, int largx,\n"
/*317*/		"             int largy, int saidatx, int saidaty,\n"
/*318*/		"             int entradatx, int entradaty,int fx, int fy,\n"
/*319*/		"             int entradatz, int k0) {\n"
/*320*/		"	int k = get_global_id(0) + k0;\n"
/*321*/		"	int x, y, filtrok;\n"
/*322*/		"	TensorRemap(k, x, y, filtrok, saidatx, saidaty)\n"
/*323*/		"	Ponto3d mapeado = {x * passox, y * passoy, 0};\n"
/*324*/		"	double sum = 0, f, v;\n"
/*325*/		"	for (int i = 0; i < fx; i++)\n"
/*326*/		"		for (int j = 0; j < fy; j++)\n"
/*327*/		"			for (int z = 0; z < entradatz; z++) {\n"
/*328*/		"				f = filtro[TensorMap4D(i, j, z, filtrok, fx, fy, entradatz)];\n"
/*329*/		"				v = entrada[TensorMap(mapeado.x + i * largx, mapeado.y + j * largy, z, entradatx, entradaty)];\n"
/*330*/		"\n"
/*331*/		"				sum += f * v;\n"
/*332*/		"			}\n"
/*333*/		"	saida[k] = sum;\n"
/*334*/		"}\n"
/*335*/		"\n"
/*336*/		"kV convncFixWeight(Vector filtro, Vector grad, Vector gradOld,\n"
/*337*/		"				   double hitlearn,\n"
/*338*/		"                   double momento, double weightDecay, int k0) {\n"
/*339*/		"	int k = get_global_id(0) + k0;\n"
/*340*/		"	double m = grad[k] + gradOld[k] * momento;\n"
/*341*/		"	double w = filtro[k];\n"
/*342*/		"	filtro[k] = w - hitlearn * (m + w * weightDecay);\n"
/*343*/		"	gradOld[k] = m;\n"
/*344*/		"}\n"
/*345*/		"\n"
/*346*/		"kV convncCalcFiltro(Vector ds,\n"
/*347*/		"                    Vector entrada,\n"
/*348*/		"                    Vector gradFiltro,\n"
/*349*/		"                    int gradFiltro_tx,\n"
/*350*/		"                    int gradFiltro_ty,\n"
/*351*/		"                    int gradFiltro_tz,\n"
/*352*/		"\n"
/*353*/		"                    int entrada_tx,\n"
/*354*/		"                    int entrada_ty,\n"
/*355*/		"\n"
/*356*/		"                    int saida_tx,\n"
/*357*/		"                    int saida_ty,\n"
/*358*/		"\n"
/*359*/		"                    int passox,\n"
/*360*/		"                    int passoy,\n"
/*361*/		"\n"
/*362*/		"                    int largx,\n"
/*363*/		"                    int largy,\n"
/*364*/		"                    int k0) {\n"
/*365*/		"	int k = get_global_id(0) + k0;\n"
/*366*/		"	int m, n, z, l;\n"
/*367*/		"	TensorRemap4D(k, m, n, z, l, gradFiltro_tx, gradFiltro_ty, gradFiltro_tz)\n"
/*368*/		"	double soma = 0,aux;\n"
/*369*/		"	for (int i = 0; i < saida_tx; ++i) {\n"
/*370*/		"		for (int j = 0; j < saida_ty; ++j) {\n"
/*371*/		"			aux = entrada[TensorMap(i * passox + m * largx, j * passoy + n * largy, z, entrada_tx, entrada_ty)]\n"
/*372*/		"			        * ds[TensorMap(i, j, l, saida_tx, saida_ty)];\n"
/*373*/		"			//aux = (!(isnan(aux) || isinf(aux)))*aux;\n"
/*374*/		"			soma += aux;\n"
/*375*/		"		}\n"
/*376*/		"	}\n"
/*377*/		"	gradFiltro[k] = soma;\n"
/*378*/		"}\n"
/*379*/		"\n"
/*380*/		"/**\n"
/*381*/		" * equacao a ser implementada\n"
/*382*/		" * x = s*p + m*w\n"
/*383*/		" * onde:\n"
/*384*/		" * 	x é da entrada \n"
/*385*/		" * 	s é da saida\n"
/*386*/		" * 	m é do filtro\n"
/*387*/		" * 	s = (x - m*w)/p\n"
/*388*/		" */\n"
/*389*/		"kV convncCalcGrads(Vector filtro,\n"
/*390*/		"                   Vector entrada,\n"
/*391*/		"                   Vector gradEntrada,\n"
/*392*/		"                   Vector gradNext,\n"
/*393*/		"\n"
/*394*/		"                   int passox,\n"
/*395*/		"                   int passoy,\n"
/*396*/		"                   int largx,\n"
/*397*/		"                   int largy,\n"
/*398*/		"\n"
/*399*/		"                   int entradatx,\n"
/*400*/		"                   int entradaty,\n"
/*401*/		"                   int saidatx,\n"
/*402*/		"                   int saidaty,\n"
/*403*/		"\n"
/*404*/		"                   int fx,\n"
/*405*/		"                   int fy,\n"
/*406*/		"                   int fz,\n"
/*407*/		"                   int numFilters,\n"
/*408*/		"\n"
/*409*/		"                   int k0) {\n"
/*410*/		"	int k = get_global_id(0) + k0;\n"
/*411*/		"	int x, y, z;\n"
/*412*/		"	TensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*413*/		"	Range range_filtro ;\n"
/*414*/		"	range_filtro.min.x = 0;\n"
/*415*/		"	if ((entradatx - x - (fx - 1) * largx) < 0) {\n"
/*416*/		"		range_filtro.min.x = -entradatx + x + fx;\n"
/*417*/		"	}\n"
/*418*/		"	range_filtro.max.x = fx - 1;\n"
/*419*/		"	if (x - (fx - 1) * largx < 0) {\n"
/*420*/		"		range_filtro.max.x = x / largx;\n"
/*421*/		"	}\n"
/*422*/		"	range_filtro.min.y = 0;\n"
/*423*/		"	if ((entradaty - y - (fy - 1) * largy) < 0) {\n"
/*424*/		"		range_filtro.min.y = -entradaty + y + fy;\n"
/*425*/		"	}\n"
/*426*/		"	range_filtro.max.y = fy - 1;\n"
/*427*/		"	if (y - (fy - 1) * largy < 0) {\n"
/*428*/		"		range_filtro.max.y = y / largy;\n"
/*429*/		"	}\n"
/*430*/		"	int sx, sy;\n"
/*431*/		"	double somaErro = 0,aux, pesoAplicado = 0;\n"
/*432*/		"	for (int m = range_filtro.min.x; m <= range_filtro.max.x; m++) {\n"
/*433*/		"		sx = (x - m * largx) / passox;\n"
/*434*/		"		if (sx * passox + m * largx != x)continue;\n"
/*435*/		"		for (int n = range_filtro.min.y; n <= range_filtro.max.y; n++) {\n"
/*436*/		"			sy = (y - n * largy) / passox;\n"
/*437*/		"			if (sy * passoy + n * largy != y)continue;\n"
/*438*/		"			for (int l = 0; l < fz; l++) {\n"
/*439*/		"				pesoAplicado = filtro[TensorMap4D(m, n, z, l, fx, fy, fz)];\n"
/*440*/		"				aux = pesoAplicado * gradNext[TensorMap(sx, sy, l, saidatx, saidaty)];\n"
/*441*/		"				//aux = (!(isnan(aux) || isinf(aux)))*aux;\n"
/*442*/		"				somaErro +=aux;\n"
/*443*/		"			}\n"
/*444*/		"		}\n"
/*445*/		"	}\n"
/*446*/		"	gradEntrada[k] = somaErro;\n"
/*447*/		"}\n"
/*448*/		"\n"
/*449*/		"\n"
/*450*/		"//dropout.h\n"
/*451*/		"#define MAX_INT_DP  ((1UL << 31) - 1)\n"
/*452*/		"long randoml(unsigned long seed,unsigned long id) {\n"
/*453*/		"	seed += id;\n"
/*454*/		"	return (seed * 0x5deece66dL + 0xbL) & MAX_INT_DP;\n"
/*455*/		"}\n"
/*456*/		"\n"
/*457*/		"double randomD(unsigned long seed,unsigned long id) {\n"
/*458*/		"	return (double) randoml(seed, id) / (double) MAX_INT_DP;\n"
/*459*/		"}\n"
/*460*/		"\n"
/*461*/		"kV dropativa(Vector entrada, Vector saida, __global char *hitmap, long seed,\n"
/*462*/		"			 double pativa, int k0) {\n"
/*463*/		"	int i = get_global_id(0) + k0;\n"
/*464*/		"//	printf(\"kernel %lf %lf %g %g\\n\",randomD(seed, i),pativa,(double)(seed +i),(double)MAX_INT_DP);\n"
/*465*/		"	char teste = (char) (randomD(seed, i) <= pativa);\n"
/*466*/		"	hitmap[i] = teste;\n"
/*467*/		"	saida[i] = teste * entrada[i];\n"
/*468*/		"}\n"
/*469*/		"\n"
/*470*/		"\n"
/*471*/		"kV dropcalcgrad(Vector gradentrada, __global char *hitmap, Vector gradnext, int k0) {\n"
/*472*/		"	int i = get_global_id(0) + k0;\n"
/*473*/		"	gradentrada[i] = hitmap[i] * gradnext[i];\n"
/*474*/		"}\n"
/*475*/		"\n"
/*476*/		"//fullconnect.h\n"
/*477*/		"double sigmoid(double x) { return 1.0 / (1.0 + exp(-x)); }\n"
/*478*/		"\n"
/*479*/		"double difsigmoid(double x) {\n"
/*480*/		"	double tmp = sigmoid(x);\n"
/*481*/		"	return tmp * (1.0 - tmp);\n"
/*482*/		"}\n"
/*483*/		"\n"
/*484*/		"double tanghG(double x) { return tanh(x); }\n"
/*485*/		"\n"
/*486*/		"double diftanhG(double x) {\n"
/*487*/		"	double tmp = tanh(x);\n"
/*488*/		"	return (1.0 - tmp * tmp);\n"
/*489*/		"}\n"
/*490*/		"\n"
/*491*/		"double relu(double x) { return x > 0 ? x : 0.0; }\n"
/*492*/		"\n"
/*493*/		"double difrelu(double x) { return x > 0 ? 1.0 : 0.0; }\n"
/*494*/		"\n"
/*495*/		"double func(int id, double x) {\n"
/*496*/		"	switch (id) {\n"
/*497*/		"		case 0:\n"
/*498*/		"			return sigmoid(x);\n"
/*499*/		"		case 1:\n"
/*500*/		"			return difsigmoid(x);\n"
/*501*/		"		case 2:\n"
/*502*/		"			return tanghG(x);\n"
/*503*/		"		case 3:\n"
/*504*/		"			return diftanhG(x);\n"
/*505*/		"		case 4:\n"
/*506*/		"			return relu(x);\n"
/*507*/		"		case 5:\n"
/*508*/		"			return difrelu(x);\n"
/*509*/		"		default:\n"
/*510*/		"			return 0;\n"
/*511*/		"	}\n"
/*512*/		"}\n"
/*513*/		"\n"
/*514*/		"kV fullfeed(Vector entrada, Vector pesos, Vector z, Vector saida,\n"
/*515*/		"			int funcaoativacao, int inx, int iny, int inz, int pesosx, int pesosy, int k0) {\n"
/*516*/		"	int m = get_global_id(0) + k0;\n"
/*517*/		"	double valorEntrada = 0;\n"
/*518*/		"	int n;\n"
/*519*/		"	for (n = 0; n < pesosy; n++) {\n"
/*520*/		"		valorEntrada += entrada[n] * pesos[TensorMap(m, n, 0, pesosx, pesosy)];\n"
/*521*/		"	}\n"
/*522*/		"	z[m] = valorEntrada;\n"
/*523*/		"	saida[m] = func(funcaoativacao, valorEntrada);\n"
/*524*/		"}\n"
/*525*/		"\n"
/*526*/		"kV fullfixweight(Vector a,\n"
/*527*/		"			  Vector pesos,\n"
/*528*/		"			  Vector dw,\n"
/*529*/		"			  Vector dz,\n"
/*530*/		"			  double hitlearn,\n"
/*531*/		"			  double decaimentoDePeso,\n"
/*532*/		"			  double momento,\n"
/*533*/		"			  int pesosy,\n"
/*534*/		"			  int k0) {\n"
/*535*/		"	int k = get_global_id(0) + k0;\n"
/*536*/		"	int m, n;\n"
/*537*/		"	m = k / pesosy;\n"
/*538*/		"	n = k % pesosy;\n"
/*539*/		"	dw[k] = dz[m] * a[n] + dw[k] * momento;\n"
/*540*/		"	pesos[k] = pesos[k] - hitlearn * (dw[k] + pesos[k] * decaimentoDePeso);\n"
/*541*/		"}\n"
/*542*/		"\n"
/*543*/		"kV fullcalcgrads1(Vector dz, Vector ds, Vector z, int dfa, int k0) {\n"
/*544*/		"	int m = get_global_id(0) + k0;\n"
/*545*/		"	dz[m] = ds[m] * func(dfa, z[m]);\n"
/*546*/		"}\n"
/*547*/		"\n"
/*548*/		"kV fullcalcgrads2(Vector dz, Vector da, Vector pesos, int pesosx, int pesosy,\n"
/*549*/		"				  int k0) {\n"
/*550*/		"	int m = get_global_id(0) + k0;\n"
/*551*/		"	double soma = 0;\n"
/*552*/		"	for (int n = 0; n < pesosx; ++n) {\n"
/*553*/		"		soma += dz[n] * pesos[TensorMap(n, m, 0, pesosx, pesosy)];\n"
/*554*/		"	}\n"
/*555*/		"	da[m] = soma;\n"
/*556*/		"}\n"
/*557*/		"\n"
/*558*/		"//padding.h\n"
/*559*/		"kV paddingfeed(Vector in,Vector out,\n"
/*560*/		"			   int txi,int tyi,\n"
/*561*/		"			   int txo,int tyo,\n"
/*562*/		"			   int t, int l ,\n"
/*563*/		"			   int k0){\n"
/*564*/		"	int k = get_global_id(0) + k0;\n"
/*565*/		"	int x, y, z;\n"
/*566*/		"	TensorRemap(k, x, y, z, txi, tyi)\n"
/*567*/		"	int s = TensorMap(x+t,y+l,z,txo,tyo);\n"
/*568*/		"	out[s] = in[k];\n"
/*569*/		"}\n"
/*570*/		"kV paddingBack(Vector gradNext,Vector gradin,\n"
/*571*/		"			   int txi,int tyi,\n"
/*572*/		"			   int txo,int tyo,\n"
/*573*/		"			   int t, int l , int k0){\n"
/*574*/		"	int k = get_global_id(0) + k0;\n"
/*575*/		"	int x, y, z;\n"
/*576*/		"	TensorRemap(k, x, y, z, txi, tyi)\n"
/*577*/		"	int s = TensorMap(x+t,y+l,z,txo,tyo);\n"
/*578*/		"	gradin[k] = gradNext[s];\n"
/*579*/		"}\n"
/*580*/		"//pool.h\n"
/*581*/		"kV poolativa(Vector entrada, Vector saida,\n"
/*582*/		"			 int passox,int passoy,\n"
/*583*/		"			 int filtrox,int filtroy,\n"
/*584*/		"			 int saidatx, int saidaty,\n"
/*585*/		"			 int entradatx, int entradaty, int k0) {\n"
/*586*/		"	int k = get_global_id(0) + k0;\n"
/*587*/		"	int x, y, z;\n"
/*588*/		"	TensorRemap(k, x, y, z, saidatx, saidaty)\n"
/*589*/		"\n"
/*590*/		"	Ponto3d mapeado = {x * passox, y * passoy, 0};\n"
/*591*/		"	double mval, v;\n"
/*592*/		"	mval = -DBL_MAX;\n"
/*593*/		"	for (int i = 0; i < filtrox; ++i) {\n"
/*594*/		"		for (int j = 0; j < filtroy; ++j) {\n"
/*595*/		"			v = entrada[TensorMap(mapeado.x + i, mapeado.y + j, z, entradatx, entradaty)];\n"
/*596*/		"			if (v > mval)\n"
/*597*/		"				mval = v;\n"
/*598*/		"		}\n"
/*599*/		"	}\n"
/*600*/		"	saida[k] = mval;\n"
/*601*/		"}\n"
/*602*/		"\n"
/*603*/		"\n"
/*604*/		"kV poolCalcGrads(Vector entrada, Vector gradEntrada,\n"
/*605*/		"				 Vector gradNext, Vector saida,\n"
/*606*/		"				 int fx, int fy, int px, int py,\n"
/*607*/		"				 int entradatx, int entradaty,\n"
/*608*/		"				 int saidatx, int saidaty,\n"
/*609*/		"				 int k0) {\n"
/*610*/		"	int k = get_global_id(0) + k0;\n"
/*611*/		"	int x, y, z;\n"
/*612*/		"	TensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*613*/		"	Range range_filtro;\n"
/*614*/		"	if (x + fx > entradatx) {\n"
/*615*/		"		range_filtro.min.x = x + fx - entradatx;\n"
/*616*/		"	}\n"
/*617*/		"	range_filtro.max.x = fx - 1;\n"
/*618*/		"	if (x - fx + 1 < 0) {\n"
/*619*/		"		range_filtro.max.x = x;\n"
/*620*/		"	}\n"
/*621*/		"	range_filtro.min.y = 0;\n"
/*622*/		"	if (y + fy > entradaty) {\n"
/*623*/		"		range_filtro.min.y = y + fy - entradaty;\n"
/*624*/		"	}\n"
/*625*/		"	range_filtro.max.y = fy - 1;\n"
/*626*/		"	if (y - fy + 1 < 0) {\n"
/*627*/		"		range_filtro.max.y = y;\n"
/*628*/		"	}\n"
/*629*/		"	int i, j;//saida\n"
/*630*/		"	gradEntrada[TensorMap(x, y, z, entradatx, entradaty)] =0;\n"
/*631*/		"	for (int m = range_filtro.min.x; m <= range_filtro.max.x; m++) {\n"
/*632*/		"		i = (x - m) / px;\n"
/*633*/		"		if (i * px + m != x)continue;\n"
/*634*/		"		for (int n = range_filtro.min.y; n <= range_filtro.max.y; n++) {\n"
/*635*/		"			j = (y - n) / py;\n"
/*636*/		"			if (j * py + n != y)continue;\n"
/*637*/		"			if (entrada[TensorMap(x, y, z, entradatx, entradaty)] ==\n"
/*638*/		"				saida[TensorMap(i, j, z, saidatx, saidaty)]) {\n"
/*639*/		"				gradEntrada[TensorMap(x, y, z, entradatx, entradaty)] =\n"
/*640*/		"						gradNext[TensorMap(i, j, z, saidatx, saidaty)];\n"
/*641*/		"				return;\n"
/*642*/		"			}\n"
/*643*/		"		}\n"
/*644*/		"	}\n"
/*645*/		"\n"
/*646*/		"}\n"
/*647*/		"\n"
/*648*/		"\n"
/*649*/		"//poolav.h\n"
/*650*/		"kV PoolAvativa(Vector entrada, Vector saida,\n"
/*651*/		"			   int passox,int passoy,\n"
/*652*/		"			   int fx,int fy,\n"
/*653*/		"			   int saidatx, int saidaty, int entradatx, int entradaty, int k0) {\n"
/*654*/		"	int k = get_global_id(0) + k0;\n"
/*655*/		"	int x, y, z;\n"
/*656*/		"	TensorRemap(k, x, y, z, saidatx, saidaty)\n"
/*657*/		"\n"
/*658*/		"	Ponto3d mapeado = {x * passox, y * passoy, 0};\n"
/*659*/		"	double soma = 0, v;\n"
/*660*/		"\n"
/*661*/		"	for (int i = 0; i < fx; ++i) {\n"
/*662*/		"		for (int j = 0; j < fy; ++j) {\n"
/*663*/		"			soma += entrada[TensorMap(mapeado.x + i, mapeado.y + j, z, entradatx, entradaty)];\n"
/*664*/		"		}\n"
/*665*/		"	}\n"
/*666*/		"	saida[k] = soma / (fx * fy);\n"
/*667*/		"}\n"
/*668*/		"\n"
/*669*/		"\n"
/*670*/		"kV PoolAvCalcGrads(Vector entrada, Vector gradEntrada, Vector gradNext, Vector saida,\n"
/*671*/		"                   int px, int py,  int fx, int fy,\n"
/*672*/		"				   int entradatx, int entradaty, int saidatx, int saidaty,\n"
/*673*/		"				   int k0) {\n"
/*674*/		"	int k = get_global_id(0) + k0;\n"
/*675*/		"	int x, y, z;\n"
/*676*/		"	TensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*677*/		"	Range range_filtro;\n"
/*678*/		"	range_filtro.min.x = 0;\n"
/*679*/		"	if (x + fx > entradatx) {\n"
/*680*/		"		range_filtro.min.x = x + fx - entradatx;\n"
/*681*/		"	}\n"
/*682*/		"	range_filtro.max.x = fx - 1;\n"
/*683*/		"	if (x - fx + 1 < 0) {\n"
/*684*/		"		range_filtro.max.x = x;\n"
/*685*/		"	}\n"
/*686*/		"	range_filtro.min.y = 0;\n"
/*687*/		"	if (y + fy > entradaty) {\n"
/*688*/		"		range_filtro.min.y = y + fy - entradaty;\n"
/*689*/		"	}\n"
/*690*/		"	range_filtro.max.y = fy - 1;\n"
/*691*/		"	if (y - fy + 1 < 0) {\n"
/*692*/		"		range_filtro.max.y = y;\n"
/*693*/		"	}\n"
/*694*/		"	int i, j;//saida\n"
/*695*/		"	double soma = 0;\n"
/*696*/		"	for (int m = range_filtro.min.x; m <= range_filtro.max.x; m++) {\n"
/*697*/		"		i = (x - m) / px;\n"
/*698*/		"		if (i * px + m != x)continue;\n"
/*699*/		"		for (int n = range_filtro.min.y; n <= range_filtro.max.y; n++) {\n"
/*700*/		"			j = (y - n) / py;\n"
/*701*/		"			if (j * py + n != y)continue;\n"
/*702*/		"			soma += gradNext[TensorMap(i, j, z, saidatx, saidaty)];\n"
/*703*/		"		}\n"
/*704*/		"	}\n"
/*705*/		"	gradEntrada[TensorMap(x, y, z, entradatx, entradaty)] = soma / (fx * fy);\n"
/*706*/		"\n"
/*707*/		"}\n"
/*708*/		"\n"
/*709*/		"\n"
/*710*/		"//relu.h\n"
/*711*/		"kV reluativa(Vector entrada, Vector saida, int k0) {\n"
/*712*/		"	int k = get_global_id(0) + k0;\n"
/*713*/		"	double v = entrada[k];\n"
/*714*/		"	if (v < 0)\n"
/*715*/		"		v = 0;\n"
/*716*/		"	saida[k] = v;\n"
/*717*/		"}\n"
/*718*/		"\n"
/*719*/		"kV relucalcgrad(Vector gradentrada, Vector entrada, Vector gradnext, int k0) {\n"
/*720*/		"	int k = get_global_id(0) + k0;\n"
/*721*/		"	gradentrada[k] = entrada[k] <= 0.0 ? (0) : gradnext[k];\n"
/*722*/		"}\n"
/*723*/		"\n"
/*724*/		"//softmax.h\n"
/*725*/		"kV SoftMaxativa1(Vector entrada, Vector exponent, Vector soma, int entradatx,\n"
/*726*/		"                 int entradaty,\n"
/*727*/		"                 int k0) {\n"
/*728*/		"	int k = get_global_id(0) + k0;\n"
/*729*/		"	int x, y, z;\n"
/*730*/		"	TensorRemap(k, x, y, z, entradatx, entradaty)\n"
/*731*/		"	exponent[k] = exp(entrada[k]);\n"
/*732*/		"	soma[z] += exponent[k];\n"
/*733*/		"}\n"
/*734*/		"\n"
/*735*/		"kV SoftMaxativa2(Vector exponet, Vector soma, Vector saida,\n"
/*736*/		"                 int saidatx, int saidaty, int k0) {\n"
/*737*/		"	int k = get_global_id(0) + k0;\n"
/*738*/		"	int x, y, z;\n"
/*739*/		"	TensorRemap(k, x, y, z, saidatx, saidaty)\n"
/*740*/		"	saida[k] = exponet[TensorMap(x, y, z, saidatx, saidaty)] / soma[z];\n"
/*741*/		"}\n"
/*742*/		"\n"
/*743*/		"kV softMaxcalcgrad(Vector gradentrada, Vector entrada, Vector gradnext, int k0) {\n"
/*744*/		"	int k = get_global_id(0) + k0;\n"
/*745*/		"	double xi = entrada[k];\n"
/*746*/		"	gradentrada[k] = xi * (1.0 - xi) * gradnext[k];\n"
/*747*/		"}\n"
/*748*/		"\n"
/*749*/		"\n"
/*750*/		"#endif //GAB_KERNELS_OPENCL_H\n"
;
const char *getInternalDefaultKernel() {
	return __default_kernel__;
}